### ISSUE TITLE
missing login

### ISSUE THREAD

**Issue by curtu** [ConnectyCube/connectycube-web-samples#100]
Hi,

We facing issues on creating the users with API. The `login` property is missing!

![image](https://user-images.githubusercontent.com/17215747/117625883-2d113f00-b17f-11eb-9e78-1c69f2e2d9fb.png)

It used to work just fine, but around last week or so, it started creating users with no login, which is creating problems when the users logs in.

An user was created on `2021-05-04T09:05:23Z` and worked it, the next one on: `2021-05-07T07:15:47Z` doesn't.

The user is still getting created, with the correct full name and external id.

This is the code that used to work. 
javascript
const axios = require('axios')
const crypto = require('crypto')
const jwt = require('jsonwebtoken')

class ConnectyCubeService {
	constructor() {
		this.config = sails.config.chat.connectycube
	}

	generateNonce = () => Math.floor(1000 + Math.random() * 9000)

	getTimestamp = () => Math.floor(new Date().getTime() / 1000)

	mapPayload = payload => {
		return Object.keys(payload)
			.map(val => {
				if (typeof payload[val] !== 'object') return `${val}=${payload[val]}`
				return Object.keys(payload[val])
					.map(val1 => `${val}[${val1}]=${payload[val][val1]}`)
					.sort()
					.join('&')
			})
			.sort()
			.join('&')
	}

	signPayload = payload => {
		return crypto
			.createHmac('sha1', sails.config.chat.connectycube.auth_secret)
			.update(this.mapPayload(payload))
			.digest('hex')
	}

	createSession = customLogin => {
		const params = {
			application_id: this.config.application_id,
			auth_key: this.config.auth_key,
			nonce: this.generateNonce(),
			timestamp: this.getTimestamp(),
		}
		if (customLogin) params.user = {
			login: 'Bearer ' + jwt.sign({
				app_metadata: {
					groupID: customLogin.group_id,
					companyID: customLogin.group_id,
					id: customLogin.id,
					role: customLogin.type
				},
				aud: sails.config.auth.clients[0].id
			}, sails.config.auth.clients[0].secret, {
				issuer: sails.config.auth.invite.issuer,
				subject: sails.config.auth.invite.subject,
				expiresIn: sails.config.auth.invite.expiresIn,
			}),
			password: HARDCODED_PASSWORD
		}
		const dataObj = { ...params, signature: this.signPayload(params) }

		return this.instance({
			url: '/session',
			method: 'post',
			data: dataObj
		})
		.then(result => _.get(result, 'data.session'))
	}

	getToken = customLogin => {
		return this.createSession(customLogin)
		.then(session => session.token)
	}

	makeRequest = (options, customLogin) => {
		return this.getToken(customLogin)
		.then(token => {
			if (_.isEmpty(options)) options = {}
			_.set(options, 'headers.CB-Token', token)

			return this.instance(options)
		})
	}

	createUser = data => {
		sails.log.debug('ConnectyCubeService.createUser:', data)

		return this.createSession(data)
		.then(session => {
			return {
				user: {
					id: _.get(session, 'user_id', null)
				}
			}
		})
	}

	updateUser = (user, data) => {
		sails.log.debug('ConnectyCubeService.updateUser:', user.chat_id, data)

		return this.makeRequest({
			method: 'put',
			url: `/users/${user.chat_id}`,
			data: {
				user: {
					full_name: [data.first_name, data.last_name].join(' ').trim()
				}
			}
		}, user)
		.then(response => response.data)
		.catch(result => Promise.reject(_.get(result, 'response.data.errors')))
	}

	deleteUser = user => {
		sails.log.debug('ConnectyCubeService.deleteUser:', user.chat_id)

		return this.makeRequest({
			method: 'delete',
			url: `/users/${user.chat_id}`
		}, user)
	}
}

module.exports = new ConnectyCubeService()

And this is how it's been configured in the dashboard:
![image](https://user-images.githubusercontent.com/17215747/117626963-5c747b80-b180-11eb-95f1-7be4be48e48c.png)

What is the problem?

**Comment by DaveLomber** [comment]
@curtu 
this should work now again 

If there is no 'login' mapping in response, then a default login will be created in format: 'custom_<uid>'

**Comment by curtu** [comment]
thank you. Yes, it works now
