### ISSUE TITLE
Searching users from dashboard not working

### ISSUE THREAD

**Issue by dozsolti** [ConnectyCube/connectycube-web-samples#105]
I've searched "Joh" in the user's list from the dashboard and only returned 1.
But I have 2 users which full names starts with John

**Comment by DaveLomber** [comment]
Please double check as it works just well 

<img width="770" alt="Screenshot 2024-12-19 at 15 50 10" src="https://github.com/user-attachments/assets/69c6fc80-c03f-46de-b910-2c0c35529500" />
