### ISSUE TITLE
error onSystemMessageListener

### ISSUE THREAD

**Issue by curtu** [ConnectyCube/connectycube-web-samples#107]
![image](https://user-images.githubusercontent.com/10010240/117973889-98047680-b335-11eb-9317-f0ebf426cb2a.png)

when trying to use ConnectyCube.chat.onSystemMessageListener i have this error

**Comment by curtu** [comment]
any info?

**Comment by DaveLomber** [comment]
A new SDK 4.0 with complete TS support has been released https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/4.0.0
Please give it a try
