### ISSUE TITLE
Can't update user data on ConnectyCube 

### ISSUE THREAD

**Issue by jddeep** [ConnectyCube/connectycube-web-samples#108]
![WhatsApp Image 2021-05-13 at 16 43 48](https://user-images.githubusercontent.com/43133646/118118894-2e569c00-b40b-11eb-9224-7ecf7cdc855a.jpeg)

```
CC_CRED = {
        appId: '**',
        authKey: '**',
        authSecret: '**',
    }

**Comment by jddeep** [comment]
@DaveLomber Please take a look. We are trying to update the user details/profile on ConnectyCube from our backend, but it doesn't work

**Comment by DaveLomber** [comment]
@jddeep what error does it produce?

**Comment by jddeep** [comment]
@DaveLomber `403: Forbidden`
```
{ code: 403, info: { errors: { base: [Array] } } }

**Comment by DaveLomber** [comment]
what's inside errors.base ?

**Comment by Sayan-dev** [comment]
@DaveLomber  
`[ 'Forbidden. Need user.' ]`

**Comment by DaveLomber** [comment]
Ok it's clear

you have to login as user or create a session with user to be able to edit yourself

Right now you have an empty session so it's not defined who you are

**Comment by jddeep** [comment]
@DaveLomber Can you please provide some demo code?
Atleast how to create a session with a user?

**Comment by DaveLomber** [comment]
either create session and then login https://developers.connectycube.com/js/authentication-and-users?id=upgrade-session-token-user-login

or just create a session with user data right here https://developers.connectycube.com/js/authentication-and-users?id=session-token-rights

```
const userCredentials = { login: "cubeuser", password: "awesomepwd" };

ConnectyCube.createSession(userCredentials)
  .then((session) => {})
  .catch((error) => {});
```

**Comment by jddeep** [comment]
This is fixed. Thanks for the help.
