### ISSUE TITLE
Add support for types.

### ISSUE THREAD

**Issue by Abhirup-99** [ConnectyCube/connectycube-web-samples#109]
It would be better if we get some official types.

**Comment by jddeep** [comment]
cc: @DaveLomber @TatankaConCube

**Comment by DaveLomber** [comment]
@Abhirup-99 @jddeep obviously we will do it at some point

**Comment by DaveLomber** [comment]
SDK 4.0 has beed released with full TS support https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/4.0.0
