### ISSUE TITLE
missing docs

### ISSUE THREAD

**Issue by krisbaum74** [ConnectyCube/connectycube-web-samples#11]
hi where is all the documentation regarding classes and JSON structures returned by your various javascript functions for ConnectyCube ?

for example  Retrieve Users By Full Name --->

const searchParams = { full_name: 'Marvin Samuel' };
 
// JS SDK v2
ConnectyCube.users
    .get(searchParams)
    .then(result => {})
    .catch(error => {});

what is the result? cannot see how anybody can build a system without this info.

**Comment by Kachanov-dev** [comment]
You can find detailed information on the site: https://developers.connectycube.com/?id=getting-started
JS SDK:  https://developers.connectycube.com/js/authentication-and-users?id=retrieve-users
Server API:  https://developers.connectycube.com/server/users?id=retrieve-users-by-full-name

**Comment by DaveLomber** [comment]
Hi @krisbaum74 
if it helps  - the JS SDK is a simple wrapper around REST API, 
so anything is returned via REST API - is the same what JS SDK returns to a user

The REST API response format can be found here https://developers.connectycube.com/server/users

Please let me know if you need any help

**Comment by ccvlad** [comment]
@krisbaum74 thank you that you have pointed on some missunderstands regarding our docs. We will add links to the REST API's response for each method.

**Comment by krisbaum74** [comment]
im also getting bugs on the  chat.dialog endpoint its not returning all my dialogs, it just returns 1 and repeats it, plus the 'name' is not correct.

can also you please point me to some live actual working websites of people using this ConnectyCube system?  


the API documentation is also incomplete. it doesnt detail filters, all the responses, or much info on the parameters required for each call..

**Comment by krisbaum74** [comment]
> Hi @krisbaum74
> if it helps - the JS SDK is a simple wrapper around REST API,
> so anything is returned via REST API - is the same what JS SDK returns to a user
> 
> The REST API response format can be found here https://developers.connectycube.com/server/users
> 
> Please let me know if you need any help

thankyou. Are you actually using ConnectyCube or do you work for them?

**Comment by ccvlad** [comment]
https://developers.connectycube.com/js/authentication-and-users?id=retrieve-users
