### ISSUE TITLE
Error on Sharing Screen on JS SDK - Unable to attach media stream, element undefined is undefined

### ISSUE THREAD

**Issue by henriquetroiano** [ConnectyCube/connectycube-web-samples#110]
I got an error on switching from camera to screen sharing:
![image](https://user-images.githubusercontent.com/63327237/118302876-23f3db00-b4bb-11eb-8e3d-8ce2b9190a10.png)

![image](https://user-images.githubusercontent.com/63327237/118302925-379f4180-b4bb-11eb-9842-7a7926acb14e.png)

**Comment by henriquetroiano** [comment]
and the function:
![image](https://user-images.githubusercontent.com/63327237/118303142-7b924680-b4bb-11eb-99a9-7c3c17eff14b.png)

**Comment by caio954** [comment]
I have the same problem too

**Comment by henriquetroiano** [comment]
they simply doesnt have the answer. Use Twilio Instead.
