### ISSUE TITLE
Public dialog unread_message_count always return 0

### ISSUE THREAD

**Issue by huahengling** [ConnectyCube/connectycube-web-samples#111]
Hi i am facing an issue where the connectycube always return 0 to me whenever i tried to get the unread_message_count for group public dialog even though i havent marked it as read yet.

**Comment by DaveLomber** [comment]
@huahengling this is expected 

there is no 'delivered/read' concept as for the public group chats.
There is only 'views_count' field is applied.


If you want to track unread count - please use regular group chats
