### ISSUE TITLE
P2P lost connection, why?

### ISSUE THREAD

**Issue by TalesBianchini** [ConnectyCube/connectycube-web-samples#112]
Please, could any one light me why the p2p video or audio call only last a few seconds? Is it because it is the free sample? How could i fix it??

**Comment by ccvlad** [comment]
No limitation such as this.
Which sample did you use? Could you send details e.g. logs, devices, steps to reproduce the issue?

**Comment by TalesBianchini** [comment]
Thank you so much for you reply! Here are the following debug lines: 
....
D/FlutterWebRTCPlugin(19366): onConnectionChangeFAILED
I/flutter (19366): CB-SDK: PeerConnection: onIceConnectionState changed to RTCIceConnectionState.RTCIceConnectionStateFailed for opponent 4292113
I/flutter (19366): CB-SDK: BaseSession: closeConnectionForOpponent, _channels.length = 0
I/flutter (19366): CB-SDK: BaseSession: closeCurrentSession
D/FlutterWebRTCPlugin(19366): onConnectionChangeCLOSED
I/flutter (19366): CB-SDK: BaseSession: _notifySessionClosed
I/flutter (19366): CB-SDK: _ConversationCallScreenState: _onSessionClosed
....

**Comment by ccvlad** [comment]
But it's Flutter, isn't it?
Please, ask in [connectycube-flutter-sdk-releases](https://github.com/ConnectyCube/connectycube-flutter-sdk-releases) repo or in [connectycube-flutter-samples](https://github.com/ConnectyCube/connectycube-flutter-samples) repo. Flutter dev will answer.
Current repository is for browsers' javascript samples.

**Comment by TalesBianchini** [comment]
Thank you!!! I'm sorry!

**Comment by ccvlad** [comment]
No problem)
