### ISSUE TITLE
My "user_id" is already in the "read_ids" although i have not send onReadStatus to connectycube

### ISSUE THREAD

**Issue by huahengling** [ConnectyCube/connectycube-web-samples#117]
Hi I need help here. Why when I only send back delivery status back to connectycube server,  and not even send onReadStatus to connectycube, connectycube already put my user id inside the read_ids for that message?

All my chat dialog type are public.

**Comment by ccvlad** [comment]
Is the user is sender? It's OK, cause sender shouldn't send statuses delivered and read on own messages

**Comment by huahengling** [comment]
no , is receiver.. receiver only send delivered status, but when request back chat history, the read_ids in this message (which receiver only send received status) contain the receiver's id

**Comment by ccvlad** [comment]
Your case:
- UserA sends message to a public dialog
- UserB receives the message and sends status delivered on the message
- UserB id contains in `message.read_ids` and in `message.delivered_ids`

Is it correct steps? I will ask our BE devs to check the issue.

**Comment by huahengling** [comment]
> Your case:
> 
> * UserA sends message to a public dialog
> * UserB receives the message and sends status delivered on the message
> * UserB id contains in `message.read_ids` and in `message.delivered_ids`
> 
> Is it correct steps? I will ask our BE devs to check the issue.

Correct. Thanks

**Comment by banshiAnton** [comment]
Hi @huahengling we deployed our changes
 Please check now

**Comment by huahengling** [comment]
> Hi @huahengling we deployed our changes
> Please check now
 
@banIn latest changes, there are no more "read_ids" and "delivered_ids" key. I need those 2 keys for my project

**Comment by banshiAnton** [comment]
This is dialog object
read_ids and delivered_ids exists in message object

**Comment by huahengling** [comment]
sorry, i didnt check properly. Tested and fixed. Thank you so much
