### ISSUE TITLE
[React] Adding default user chat on app launch

### ISSUE THREAD

**Issue by andrezg98** [ConnectyCube/connectycube-web-samples#123]
Hi! I have used the template from [here](https://github.com/ConnectyCube/connectycube-web-samples/tree/master/chat) but I am trying to setup the chat so that by default, when the app opens, one chat prompt with a predetermined user opens (like in the following screenshot that I have added manually). In the template, by the default the chat list is empty. How can I do this?

![Issue](https://user-images.githubusercontent.com/47974850/123227169-9e5d4500-d4d4-11eb-9a19-e1b1aae2d1b6.PNG)

**Comment by ccvlad** [comment]
Hi @andrezg98 

You can call [goToDialog(dialogItem)](https://github.com/ConnectyCube/connectycube-web-samples/blob/master/chat/src/components/home/sideBar/dialogs/dialogs.js#L99) method from start and pass a dialog as param.

Or use some dialog as default property (e.g. `currentDialog = selectedDialog ? selectedDialog : dialogsList[0]`) on chat screen.

**Comment by andrezg98** [comment]
Thanks a lot, I think it works!
