### ISSUE TITLE
require('connectycube') returns empty object in Node 12

### ISSUE THREAD

**Issue by whenmoon** [ConnectyCube/connectycube-web-samples#125]
I am initialising ConnectyCube inside a Firebase Cloud Function (serverless function), but the require returns an empty object:

```javascript
const connectyCube = require('connectycube');

		console.log('connectyCube >>>>>>>>>>>>>>>>>>>>>>>>>>>>', JSON.stringify(connectyCube));
		console.log('connectyCube.init >>>>>>>>>>>>>>>>>>>>>>>', JSON.stringify(connectyCube.init));
```
![Screenshot 2021-06-25 at 15 32 32](https://user-images.githubusercontent.com/33122888/123432392-a13a6180-d5ca-11eb-8d6f-3c811df308da.png)

package.json:
```json
  "engines": {
    "node": "12"
  },
  "dependencies": {
    "connectycube": "3.10.0",
    "firebase-admin": "^9.10.0",
    "firebase-functions": "^3.14.1"
  },
```
I have tested for circular dependencies but it seems fine.

Do you know what could be the cause of the problem?

Thanks.

**Comment by ccvlad** [comment]
Hi @whenmoon 

Try `const ConnectyCube = require('node_modules/connectycube/lib/cubeMain.js');`

I didn't manage to reproduce:
<img width="1163" alt="Screen Shot 2021-06-25 at 16 58 31" src="https://user-images.githubusercontent.com/43810932/123436395-43604680-d5d7-11eb-8343-23b580455217.png">

**Comment by ccvlad** [comment]
@DaveLomber did you ever tried install ConnectyCube inside the Firebase Cloud Function?

**Comment by whenmoon** [comment]
Thanks @ccvlad, it strange because this has been working for me for a long time but now it has stopped working.

I tried what you suggested and it doesn't work. I'll investigate further and let you know what I find.

**Comment by whenmoon** [comment]
Marking this as closed as resolved on my side but still have issues initialising the app - will create another issue if necessary
