### ISSUE TITLE
[React] (InvalidStateError): Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by andrezg98** [ConnectyCube/connectycube-web-samples#126]
Hi, I'm having a problem sending a default message in chat when creating a new dialog and I'm not quite sure what could be wrong.

The error is as follows:

> **`Unhandled Rejection (InvalidStateError): Failed to execute 'send' on 'WebSocket': Still in CONNECTING state`**.

Once the dialog parameters were defined and the dialog was created, the message was created like this:

> ![image](https://user-images.githubusercontent.com/47974850/125042525-385aeb00-e09a-11eb-92f4-941f61e14da0.png)

I call the whole function from render() and this may be where the state problem is.

If anyone has any idea what might be wrong, it would be a great help.

Thanks!

**Comment by DaveLomber** [comment]
I suggest to follow the Send 1st message guide https://developers.connectycube.com/js/getting-started/send-first-chat-message/

Most probably the issue related that you need to wait until `ConnectyCube.chat.connect` is finished so then you should be able to send messages
