### ISSUE TITLE
Cannot Delete chat dialog from nodejs server

### ISSUE THREAD

**Issue by Sayan-dev** [ConnectyCube/connectycube-web-samples#133]
- This is the code
![Screenshot from 2021-08-24 18-40-33](https://user-images.githubusercontent.com/42710260/130622365-a10a88c9-3a40-4e83-a318-d10bca3e0377.png)

- This is the error
![Screenshot from 2021-08-24 18-41-02](https://user-images.githubusercontent.com/42710260/130622384-149823aa-21cf-49e1-bb93-efafac48e8a3.png)

Please help me understand what token do I require here

**Comment by Sayan-dev** [comment]
- Added this step
![advance](https://user-images.githubusercontent.com/42710260/130623029-c442e5f8-5ea2-4d84-befb-fc4a081184d4.png)
- This is the new error
![advanceerr](https://user-images.githubusercontent.com/42710260/130623041-300262d8-b424-45c1-9011-12168c58a363.png)

Which user do I require can you state

**Comment by jddeep** [comment]
@TatankaConCube @DaveLomber Please take a look

**Comment by TatankaConCube** [comment]
You get this error because you have the session without user. Create the session with user first.

**Comment by Sayan-dev** [comment]
I want to delete the dialog.....which user do I need

**Comment by TatankaConCube** [comment]
Only dialog member can delete it for himself and dialog owner can delete it completely.

**Comment by Sayan-dev** [comment]
Can you specify who is the dialog owner?

**Comment by TatankaConCube** [comment]
https://developers.connectycube.com/server/chat?id=roles-and-privileges here more obout roles of users in the dialog

**Comment by jddeep** [comment]
@TatankaConCube so when a regular user creates a chat dialog is he automatically a super admin or do we need to make that user super admin somehow. Please share how we can do so

**Comment by TatankaConCube** [comment]
Yes, you a right, any user, who creates the dialog automaticlay becomes the super admin for this dialog.

**Comment by Sayan-dev** [comment]
Ok issue solved, thankyou @TatankaConCube

**Comment by Sayan-dev** [comment]
The parameter `force=1` is only needed to be added. For example:
`ConnectyCube.chat.dialog.delete(dialogueId, {
            force: 1,
        })`
