### ISSUE TITLE
  node.js server error CallType of Null

### ISSUE THREAD

**Issue by krisbaum74** [ConnectyCube/connectycube-web-samples#14]
get error -> error initialisingTypeError: Cannot read property 'CallType' of null

code-->

const http = require('http');
var ccube = require('connectycube');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
res.statusCode = 200;
res.setHeader('Content-Type', 'text/plain');
res.end('Hello World');

// let urlParams = getParams(window.location.href);
});

server.listen(port, hostname, () => {
console.log(Server running at http://${hostname}:${port}/);

const CONNECTYCUBE_APPLICATION_ID = xxxx;
const CONNECTYCUBE_AUTHORIZATION_KEY = xxxxx
const CONNECTYCUBE_AUTHORIZATION_SECRET = xxxxx

const CONNECTYCUBE_CREDENTIALS = {
appId: CONNECTYCUBE_APPLICATION_ID,
authKey: CONNECTYCUBE_AUTHORIZATION_KEY,
authSecret: CONNECTYCUBE_AUTHORIZATION_SECRET
};

ccube.init(CONNECTYCUBE_CREDENTIALS);

let userCredentials = {
userId: xxxxx,
password: xxxx
};

ccube.chat
.connect(userCredentials)
.then(() => {

const calleesIds = [1197559]; // User's ids
const _sessionType = ccube.videochat.CallType.VIDEO; // AUDIO is also possible
const additionalOptions = {};
const _session = ccube.videochat.createNewSession(calleesIds, _sessionType, additionalOptions);

res.end('Hello World' + _session);

**Comment by ccvlad** [comment]
https://github.com/ConnectyCube/connectycube-js-sdk-releases/issues/14#issuecomment-609558455
