### ISSUE TITLE
Call Browser to App Flutter

### ISSUE THREAD

**Issue by nambui2000k** [ConnectyCube/connectycube-web-samples#142]
Can I call P2P from Browser to App Flutter?
I try call from App flutter to Browser that right. But run from Browser to App Flutter which can not recieve notification.

**Comment by nambui2000k** [comment]
<img width="609" alt="Screen Shot 2021-10-21 at 23 41 36" src="https://user-images.githubusercontent.com/49670327/138320987-e16f9ae0-6924-4102-8b9f-073dc812e081.png">
_getCallState only has ios and android?

**Comment by TatankaConCube** [comment]
no, if you don't need the push notifications feature on the JS side
