### ISSUE TITLE
Call not connecting on cross browsers and mobile responsive view

### ISSUE THREAD

**Issue by shrinidhi2310** [ConnectyCube/connectycube-web-samples#186]
Hi there,

We are trying to integrate the p2p video call functionality of connectycube for our website. We are following this document for the integration. https://developers.connectycube.com/js/

We checked the demo for the call functionality,
i) The demo works fine when the caller and callee are using the same browser. For eg, user A and user B are both using chrome then the call is working fine. But if user A is using chrome and user B is using Firefox browser, then the call is not received. 

ii) If user A is using a chrome browser from a laptop/system and user B is using the chrome browser on mobile, then the call is not connected between them.

The same issues on the demo URL occur on the code we have integrated based on the document also.  Could you kindly let us know what causes these issues? 
The demo link we have used for checking- https://connectycube.github.io/connectycube-web-samples/videochat/dist/

Thanks in advance.

**Comment by kavitamatondkar** [comment]
Hi. Did anyone found solution for this?

**Comment by DaveLomber** [comment]
The ConnectyCube calls are supported by all major browsers.

Please specify what exact issue are you facing when call other browser.

Also, I suggest to clone the code sample, and put your own ConnectyCUbe app credentials, so you will have an isolated environment to test
