### ISSUE TITLE
couldn't run react app

### ISSUE THREAD

**Issue by choco-code** [ConnectyCube/connectycube-web-samples#19]
Where to give credentials?

**Comment by DaveLomber** [comment]
Please follow the getting started guide https://developers.connectycube.com/?id=getting-started

You need to register a new account at https://admin.connectycube.com and then create an app there, which then will give you the credentials

**Comment by ccvlad** [comment]
I have closed the issue due inactivity. Please raise a separate issue in case of any other questions.
