### ISSUE TITLE
How to create an event from the browser side for all call members, how we do it on the javascript side, so we can call it on flutter

### ISSUE THREAD

**Issue by saimohanayinam** [ConnectyCube/connectycube-web-samples#191]
How to create an event from the browser side for all call members, how we do it on the javascript side, so we can call it on flutter

**Comment by TatankaConCube** [comment]
@saimohanayinam please follow this [doc](https://developers.connectycube.com/js/push-notifications?id=send-push-notifications) for creation events on the JS side

**Comment by saimohanayinam** [comment]
done working
