### ISSUE TITLE
While we are sending images from mobile (flutter) to web(React js) the images are not showing and we are unable to see the image(showing error) in mobile(flutter) while sending from web(React js)

### ISSUE THREAD

**Issue by saimohanayinam** [ConnectyCube/connectycube-web-samples#208]
![image](https://user-images.githubusercontent.com/83359823/180752060-0e49bec1-7dd7-4e4e-9be7-902601b51a46.png)

![image](https://user-images.githubusercontent.com/83359823/180752130-cc97bf80-eeca-4cd3-aea6-ecb6874e44a5.png)

**Comment by TatankaConCube** [comment]
@saimohanayinam could you please share here the log from both sides (flutter and web) which contains the sent messages from both platforms. Looks like you send the attachment in a different way on separated platforms.

**Comment by saimohanayinam** [comment]
import 'dart:async';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:collection/collection.dart' show IterableExtension;
import 'package:file_picker/file_picker.dart';
import 'package:flutter/foundation.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:intl/intl.dart';
import 'package:connectycube_sdk/connectycube_sdk.dart';
import 'package:flutter/material.dart';
import 'package:patientsoundheart/constants/values.dart';
import 'package:patientsoundheart/services/Communication/widgets/Chat/chat_list.dart';
import 'package:patientsoundheart/services/Doctors/middleware/doctors_middleware.dart';
import 'package:patientsoundheart/services/Doctors/model/DoctorsList/doctor_model.dart';
import 'package:patientsoundheart/services/Doctors/widgets/DoctorProfile/appointment.dart';
import 'package:patientsoundheart/shared/widgets/base/base_state.dart';
import 'package:patientsoundheart/services/Communication/middleware/chat.dart';
import 'package:patientsoundheart/services/Communication/widgets/Video/src/managers/call_manager.dart';
// import 'package:patientsoundheartt/services/Communication/middleware/chat.dart';
import 'package:patientsoundheart/shared/widgets/loading.dart';
import 'package:patientsoundheart/shared/widgets/snackbars.dart';
import 'package:universal_io/io.dart';
import 'common.dart';

class ViewChat extends StatefulWidget {
  final CubeUser cubeUser;
  final CubeDialog cubeDialog;

  ViewChat({required this.cubeDialog, required this.cubeUser});

  @override
  _ViewChatState createState() => _ViewChatState();
}

class _ViewChatState extends BaseState<ViewChat> {
  static const String TAG = "_CreateChatScreenState";

  final Map<int?, CubeUser?> _occupants = Map();

  late bool isLoading;
  String? imageUrl;
  List<CubeMessage>? listMessage = [];
  Timer? typingTimer;
  bool isTyping = false;
  String userStatus = '';

  final TextEditingController textEditingController = TextEditingController();
  final ScrollController listScrollController = ScrollController();

  StreamSubscription<CubeMessage>? msgSubscription;
  StreamSubscription<MessageStatus>? deliveredSubscription;
  StreamSubscription<MessageStatus>? readSubscription;
  StreamSubscription<TypingStatus>? typingSubscription;

  List<CubeMessage> _unreadMessages = [];
  List<CubeMessage> _unsentMessages = [];

  @override
  void initState() {
    super.initState();
    _initCubeChat();

    isLoading = false;
    imageUrl = '';
  }

  @override
  void dispose() {
    msgSubscription?.cancel();
    deliveredSubscription?.cancel();
    readSubscription?.cancel();
    typingSubscription?.cancel();
    textEditingController.dispose();
    super.dispose();
  }

  void openGallery() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.image,
    );

    if (result == null) return;

    setState(() {
      isLoading = true;
    });

    var uploadImageFuture = getUploadingImageFuture(result);
    var imageData;

    if (kIsWeb) {
      imageData = result.files.single.bytes!;
    } else {
      imageData = File(result.files.single.path!).readAsBytesSync();
    }

    var decodedImage = await decodeImageFromList(imageData);

    uploadImageFile(uploadImageFuture, decodedImage);
  }

  Future uploadImageFile(Future<CubeFile> uploadAction, imageData) async {
    uploadAction.then((cubeFile) {
      onSendChatAttachment(cubeFile, imageData);
    }).catchError((ex) {
      setState(() {
        isLoading = false;
      });
      Fluttertoast.showToast(msg: 'This file is not an image');
    });
  }

  void onReceiveMessage(CubeMessage message) {
    log("onReceiveMessage message= $message");
    if (message.dialogId != widget.cubeDialog.dialogId || message.senderId == widget.cubeUser.id)
      return;

    widget.cubeDialog.deliverMessage(message);
    addMessageToListView(message);
  }

  void onDeliveredMessage(MessageStatus status) {
    log("onDeliveredMessage message= $status");
    updateReadDeliveredStatusMessage(status, false);
  }

  void onReadMessage(MessageStatus status) {
    log("onReadMessage message= ${status.messageId}");
    updateReadDeliveredStatusMessage(status, true);
  }

  void onTypingMessage(TypingStatus status) {
    log("TypingStatus message= ${status.userId}");
    if (status.userId == widget.cubeUser.id ||
        (status.dialogId != null && status.dialogId != widget.cubeDialog.dialogId)) return;
    userStatus = _occupants[status.userId]?.fullName ?? _occupants[status.userId]?.login ?? '';
    if (userStatus.isEmpty) return;
    userStatus = "$userStatus is typing ...";

    if (isTyping != true) {
      setState(() {
        isTyping = true;
      });
    }
    startTypingTimer();
  }

  startTypingTimer() {
    typingTimer?.cancel();
    typingTimer = Timer(Duration(milliseconds: 900), () {
      setState(() {
        isTyping = false;
      });
    });
  }

  void onSendChatMessage(String content) {
    if (content.trim() != '') {
      final message = createCubeMsg();
      message.body = content.trim();
      onSendMessage(message);
    } else {
      Fluttertoast.showToast(msg: 'Nothing to send');
    }
  }

  void onSendChatAttachment(CubeFile cubeFile, imageData) async {
    final attachment = CubeAttachment();
    attachment.id = cubeFile.uid;
    attachment.type = CubeAttachmentType.IMAGE_TYPE;
    attachment.url = cubeFile.getPublicUrl();
    attachment.height = imageData.height;
    attachment.width = imageData.width;
    final message = createCubeMsg();
    message.body = "Attachment";
    message.attachments = [attachment];
    onSendMessage(message);
  }

  CubeMessage createCubeMsg() {
    var message = CubeMessage();
    message.dateSent = DateTime.now().millisecondsSinceEpoch ~/ 1000;
    message.markable = true;
    message.saveToHistory = true;
    return message;
  }

  void onSendMessage(CubeMessage message) async {
    log("onSendMessage message= $message");
    textEditingController.clear();
    await widget.cubeDialog.sendMessage(message);
    message.senderId = widget.cubeUser.id;
    addMessageToListView(message);
    listScrollController.animateTo(0.0,
        duration: Duration(milliseconds: 300), curve: Curves.easeOut);
  }

  updateReadDeliveredStatusMessage(MessageStatus status, bool isRead) {
    log('[updateReadDeliveredStatusMessage]');
    setState(() {
      CubeMessage? msg = listMessage!.firstWhereOrNull((msg) => msg.messageId == status.messageId);
      if (msg == null) return;
      if (isRead)
        msg.readIds == null ? msg.readIds = [status.userId] : msg.readIds?.add(status.userId);
      else
        msg.deliveredIds == null
            ? msg.deliveredIds = [status.userId]
            : msg.deliveredIds?.add(status.userId);

      log('[updateReadDeliveredStatusMessage] status updated for $msg');
    });
  }

  addMessageToListView(CubeMessage message) {
    setState(() {
      isLoading = false;
      int existMessageIndex = listMessage!.indexWhere((cubeMessage) {
        return cubeMessage.messageId == message.messageId;
      });

      if (existMessageIndex != -1) {
        listMessage!.replaceRange(existMessageIndex, existMessageIndex + 1, [message]);
      } else {
        listMessage!.insert(0, message);
      }
    });
  }

  @override
  getAppBar() {
    return AppBar(
      backgroundColor: AppColors.appBarColor,
      elevation: 0,
      leading: Align(
        alignment: Alignment.topCenter,
        child: IconButton(
          icon: Icon(Icons.arrow_back_ios),
          color: AppColors.white,
          onPressed: () {
            Navigator.pop(context);
            mapDispatchToProps(getAllChats());
          },
        ),
      ),
      title: Row(
        children: [
          Flexible(
            flex: 2,
            child: GestureDetector(
              onTap: () {},
              child: CircleAvatar(
                backgroundImage: widget.cubeDialog.photo?.isNotEmpty == true
                    ? NetworkImage(widget.cubeUser.avatar!)
                    : AssetImage(CustomIcon.DEFAULT_DOCTOR_IMAGE) as ImageProvider,
              ),
            ),
          ),
          Flexible(
            flex: 10,
            child: Container(
              margin: EdgeInsets.only(left: 10),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    widget.cubeDialog.name ?? '',
                    style: TextStyle(
                      fontFamily: 'Montserrat',
                      color: Colors.white,
                      fontSize: 18,
                      fontWeight: FontWeight.w700,
                      fontStyle: FontStyle.normal,
                      letterSpacing: 0.54,
                    ),
                  ),
                  // Text(
                  //   "",
                  //   style: TextStyle(
                  //     fontFamily: 'Montserrat',
                  //     color: AppColors.turquoiseBlue,
                  //     fontSize: 12,
                  //     fontWeight: FontWeight.w400,
                  //     fontStyle: FontStyle.normal,
                  //   ),
                  // )
                ],
              ),
            ),
          )
        ],
      ),
      actions: [
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: InkWell(
            onTap: () async {
              List<int> occupantIds = widget.cubeDialog.occupantsIds!;
              int otherPersonId = occupantIds.where((id) => id != widget.cubeUser.id).first;
              DoctorModel doctor = await getDoctorFromConnectyCubeId(otherPersonId);
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => Appointment(
                    appointmentType: 0,
                    doctor: doctor,
                  ),
                ),
              );
            },
            child: Icon(
              Icons.phone,
              size: 25,
              color: AppColors.turquoiseBlue,
            ),
          ),
        ),
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: InkWell(
            onTap: () async {
              List<int> occupantIds = widget.cubeDialog.occupantsIds!;
              int otherPersonId = occupantIds.where((id) => id != widget.cubeUser.id).first;
              DoctorModel doctor = await getDoctorFromConnectyCubeId(otherPersonId);
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => Appointment(
                    appointmentType: 1,
                    doctor: doctor,
                  ),
                ),
              );
            },
            child: Icon(
              Icons.videocam,
              size: 25,
              color: AppColors.turquoiseBlue,
            ),
          ),
        ),
      ],
    );
  }

  @override
  getPageContainer() {
    return WillPopScope(
      child: Stack(
        children: <Widget>[
          Column(
            children: <Widget>[
              // List of messages
              buildListMessage(),
              //Typing content
              buildTyping(),
              // Input content
              buildInput(),
            ],
          ),

          // Loading
          buildLoading()
        ],
      ),
      onWillPop: onBackPress,
    );
  }

  Widget buildItem(int index, CubeMessage message) {
    markAsReadIfNeed() {
      var isOpponentMsgRead =
          message.readIds != null && message.readIds!.contains(widget.cubeUser.id);
      print("markAsReadIfNeed message= $message, isOpponentMsgRead= $isOpponentMsgRead");
      if (message.senderId != widget.cubeUser.id && !isOpponentMsgRead) {
        if (message.readIds == null) {
          message.readIds = [widget.cubeUser.id!];
        } else {
          message.readIds!.add(widget.cubeUser.id!);
        }

        if (CubeChatConnection.instance.chatConnectionState == CubeChatConnectionState.Ready) {
          widget.cubeDialog.readMessage(message);
        } else {
          _unreadMessages.add(message);
        }
      }
    }

    Widget getReadDeliveredWidget() {
      log("[getReadDeliveredWidget]");
      bool messageIsRead() {
        log("[getReadDeliveredWidget] messageIsRead");
        if (widget.cubeDialog.type == CubeDialogType.PRIVATE)
          return message.readIds != null &&
              (message.recipientId == null || message.readIds!.contains(message.recipientId));
        return message.readIds != null &&
            message.readIds!
                .any((int id) => id != widget.cubeUser.id && _occupants.keys.contains(id));
      }

      bool messageIsDelivered() {
        log("[getReadDeliveredWidget] messageIsDelivered");
        if (widget.cubeDialog.type == CubeDialogType.PRIVATE)
          return message.deliveredIds?.contains(message.recipientId) ?? false;
        return message.deliveredIds != null &&
            message.deliveredIds!
                .any((int id) => id != widget.cubeUser.id && _occupants.keys.contains(id));
      }

      if (messageIsRead()) {
        log("[getReadDeliveredWidget] if messageIsRead");
        return Stack(children: <Widget>[
          Icon(
            Icons.check,
            size: 15.0,
            color: AppColors.blueColor,
          ),
          Padding(
            padding: EdgeInsets.only(left: 8),
            child: Icon(
              Icons.check,
              size: 15.0,
              color: AppColors.blueColor,
            ),
          )
        ]);
      } else if (messageIsDelivered()) {
        log("[getReadDeliveredWidget] if messageIsDelivered");
        return Stack(children: <Widget>[
          Icon(
            Icons.check,
            size: 15.0,
            color: AppColors.greyColor,
          ),
          Padding(
            padding: EdgeInsets.only(left: 8),
            child: Icon(
              Icons.check,
              size: 15.0,
              color: AppColors.greyColor,
            ),
          )
        ]);
      } else {
        log("[getReadDeliveredWidget] sent");
        return Icon(
          Icons.check,
          size: 15.0,
          color: AppColors.greyColor,
        );
      }
    }

    Widget getDateWidget() {
      return Text(
        DateFormat('HH:mm').format(DateTime.fromMillisecondsSinceEpoch(message.dateSent! * 1000)),
        style: TextStyle(color: AppColors.greyColor, fontSize: 12.0, fontStyle: FontStyle.italic),
      );
    }

    Widget getHeaderDateWidget() {
      return Container(
        alignment: Alignment.center,
        child: Text(
          DateFormat('dd MMMM yyyy')
              .format(DateTime.fromMillisecondsSinceEpoch(message.dateSent! * 1000)),
          style: BaseStyles.subTitleStyle,
        ),
        margin: EdgeInsets.all(10.0),
      );
    }

    bool isHeaderView() {
      int headerId = int.parse(DateFormat('ddMMyyyy')
          .format(DateTime.fromMillisecondsSinceEpoch(message.dateSent! * 1000)));
      if (index >= listMessage!.length - 1) {
        return false;
      }
      var msgPrev = listMessage![index + 1];
      int nextItemHeaderId = int.parse(DateFormat('ddMMyyyy')
          .format(DateTime.fromMillisecondsSinceEpoch(msgPrev.dateSent! * 1000)));
      var result = headerId != nextItemHeaderId;
      return result;
    }

    if (message.senderId == widget.cubeUser.id) {
      // Right (own message)
      return Column(
        children: <Widget>[
          isHeaderView() ? getHeaderDateWidget() : SizedBox.shrink(),
          Row(
            children: <Widget>[
              message.attachments?.isNotEmpty ?? false
                  // Image
                  ? Container(
                      child: TextButton(
                        child: Material(
                          child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [
                            CachedNetworkImage(
                              placeholder: (context, url) => Container(
                                child: CircularProgressIndicator(
                                  valueColor: AlwaysStoppedAnimation<Color>(AppColors.themeColor),
                                ),
                                width: 200.0,
                                height: 200.0,
                                padding: EdgeInsets.all(70.0),
                                decoration: BoxDecoration(
                                  color: AppColors.greyColor2,
                                  borderRadius: BorderRadius.all(
                                    Radius.circular(8.0),
                                  ),
                                ),
                              ),
                              errorWidget: (context, url, error) => Material(
                                child: Image.asset(
                                  'images/img_not_available.jpeg',
                                  width: 200.0,
                                  height: 200.0,
                                  fit: BoxFit.cover,
                                ),
                                borderRadius: BorderRadius.all(
                                  Radius.circular(8.0),
                                ),
                                clipBehavior: Clip.hardEdge,
                              ),
                              imageUrl: message.attachments!.first.url!,
                              width: 200.0,
                              height: 200.0,
                              fit: BoxFit.cover,
                            ),
                            getDateWidget(),
                            getReadDeliveredWidget(),
                          ]),
                          borderRadius: BorderRadius.all(Radius.circular(8.0)),
                          clipBehavior: Clip.hardEdge,
                        ),
                        onPressed: () {},
                        // onPressed: () {
                        //   Navigator.push(
                        //       context,
                        //       MaterialPageRoute(
                        //           builder: (context) =>
                        //               FullPhoto(url: message.attachments!.first.url!)));
                        // },
                      ),
                      margin: EdgeInsets.only(
                          bottom: isLastMessageRight(index) ? 20.0 : 10.0, right: 10.0),
                    )
                  : message.body != null && message.body!.isNotEmpty
                      // Text
                      ? Flexible(
                          child: Container(
                            padding: EdgeInsets.fromLTRB(15.0, 10.0, 15.0, 10.0),
                            decoration: BoxDecoration(
                                color: AppColors.greyColor2,
                                borderRadius: BorderRadius.circular(8.0)),
                            margin: EdgeInsets.only(
                                bottom: isLastMessageRight(index) ? 20.0 : 10.0, right: 10.0),
                            child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [
                              Text(
                                message.body!,
                                style: TextStyle(color: AppColors.primaryColor),
                              ),
                              getDateWidget(),
                              getReadDeliveredWidget(),
                            ]),
                          ),
                        )
                      : Container(
                          child: Text(
                            "Empty",
                            style: TextStyle(color: AppColors.primaryColor),
                          ),
                          padding: EdgeInsets.fromLTRB(15.0, 10.0, 15.0, 10.0),
                          width: 200.0,
                          decoration: BoxDecoration(
                              color: AppColors.greyColor2,
                              borderRadius: BorderRadius.circular(8.0)),
                          margin: EdgeInsets.only(
                              bottom: isLastMessageRight(index) ? 20.0 : 10.0, right: 10.0),
                        ),
            ],
            mainAxisAlignment: MainAxisAlignment.end,
          ),
        ],
      );
    } else {
      // Left (opponent message)
      markAsReadIfNeed();
      return Container(
        child: Column(
          children: <Widget>[
            isHeaderView() ? getHeaderDateWidget() : SizedBox.shrink(),
            Row(
              children: <Widget>[
                Material(
                  child: CircleAvatar(
                    backgroundImage: _occupants[message.senderId]?.avatar != null &&
                            _occupants[message.senderId]!.avatar!.isNotEmpty
                        ? NetworkImage(_occupants[message.senderId]!.avatar!)
                        : null,
                    backgroundColor: AppColors.greyColor2,
                    radius: 25,
                    child: getAvatarTextWidget(
                      _occupants[message.senderId]?.avatar != null &&
                          _occupants[message.senderId]!.avatar!.isNotEmpty,
                      _occupants[message.senderId]?.fullName?.substring(0, 2).toUpperCase(),
                    ),
                  ),
                  borderRadius: BorderRadius.all(
                    Radius.circular(18.0),
                  ),
                  clipBehavior: Clip.hardEdge,
                ),
                message.attachments?.isNotEmpty ?? false
                    ? Container(
                        child: TextButton(
                          child: Material(
                            child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                              CachedNetworkImage(
                                placeholder: (context, url) => Container(
                                  child: CircularProgressIndicator(
                                    valueColor: AlwaysStoppedAnimation<Color>(AppColors.themeColor),
                                  ),
                                  width: 200.0,
                                  height: 200.0,
                                  padding: EdgeInsets.all(70.0),
                                  decoration: BoxDecoration(
                                    color: AppColors.greyColor2,
                                    borderRadius: BorderRadius.all(
                                      Radius.circular(8.0),
                                    ),
                                  ),
                                ),
                                errorWidget: (context, url, error) => Material(
                                  child: Image.asset(
                                    'images/img_not_available.jpeg',
                                    width: 200.0,
                                    height: 200.0,
                                    fit: BoxFit.cover,
                                  ),
                                  borderRadius: BorderRadius.all(
                                    Radius.circular(8.0),
                                  ),
                                  clipBehavior: Clip.hardEdge,
                                ),
                                imageUrl: message.attachments!.first.url!,
                                width: 200.0,
                                height: 200.0,
                                fit: BoxFit.cover,
                              ),
                              getDateWidget(),
                            ]),
                            borderRadius: BorderRadius.all(Radius.circular(8.0)),
                            clipBehavior: Clip.hardEdge,
                          ),
                          onPressed: () {},
                          // onPressed: () {
                          //   Navigator.push(
                          //       context,
                          //       MaterialPageRoute(
                          //           builder: (context) =>
                          //               FullPhoto(url: message.attachments!.first.url!)));
                          // },
                        ),
                        margin: EdgeInsets.only(left: 10.0),
                      )
                    : message.body != null && message.body!.isNotEmpty
                        ? Flexible(
                            child: Container(
                              padding: EdgeInsets.fromLTRB(15.0, 10.0, 15.0, 10.0),
                              decoration: BoxDecoration(
                                  color: AppColors.primaryColor,
                                  borderRadius: BorderRadius.circular(8.0)),
                              margin: EdgeInsets.only(left: 10.0),
                              child:
                                  Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                                Text(
                                  message.body!,
                                  style: TextStyle(color: Colors.white),
                                ),
                                getDateWidget(),
                              ]),
                            ),
                          )
                        : Container(
                            child: Text(
                              "Empty",
                              style: TextStyle(color: AppColors.primaryColor),
                            ),
                            padding: EdgeInsets.fromLTRB(15.0, 10.0, 15.0, 10.0),
                            width: 200.0,
                            decoration: BoxDecoration(
                                color: AppColors.greyColor2,
                                borderRadius: BorderRadius.circular(8.0)),
                            margin: EdgeInsets.only(
                                bottom: isLastMessageRight(index) ? 20.0 : 10.0, right: 10.0),
                          ),
              ],
            ),
          ],
          crossAxisAlignment: CrossAxisAlignment.start,
        ),
        margin: EdgeInsets.only(bottom: 10.0),
      );
    }
  }

  bool isLastMessageLeft(int index) {
    if ((index > 0 && listMessage != null && listMessage![index - 1].id == widget.cubeUser.id) ||
        index == 0) {
      return true;
    } else {
      return false;
    }
  }

  bool isLastMessageRight(int index) {
    if ((index > 0 && listMessage != null && listMessage![index - 1].id != widget.cubeUser.id) ||
        index == 0) {
      return true;
    } else {
      return false;
    }
  }

  Widget buildLoading() {
    return Positioned(
      child: isLoading ? Loading() : Container(),
    );
  }

  Widget buildTyping() {
    return Visibility(
      visible: isTyping,
      child: Container(
        child: Text(
          userStatus,
          style: TextStyle(color: AppColors.primaryColor),
        ),
        alignment: Alignment.centerLeft,
        margin: EdgeInsets.all(16.0),
      ),
    );
  }

  Widget buildInput() {
    return Container(
      child: Row(
        children: <Widget>[
          // Button send image
          Material(
            child: Container(
              margin: EdgeInsets.symmetric(horizontal: 1.0),
              child: IconButton(
                icon: Icon(Icons.image),
                onPressed: () {
                  openGallery();
                },
                color: AppColors.primaryColor,
              ),
            ),
            color: Colors.white,
          ),

          // Edit text
          Flexible(
            child: Container(
              child: TextField(
                style: TextStyle(color: AppColors.primaryColor, fontSize: 15.0),
                controller: textEditingController,
                decoration: InputDecoration.collapsed(
                  hintText: 'Type your message...',
                  hintStyle: TextStyle(color: AppColors.greyColor),
                ),
                onChanged: (text) {
                  widget.cubeDialog.sendIsTypingStatus();
                },
              ),
            ),
          ),

          // Button send message
          Material(
            child: Container(
              margin: EdgeInsets.symmetric(horizontal: 8.0),
              child: IconButton(
                icon: Icon(Icons.send),
                onPressed: () => onSendChatMessage(textEditingController.text),
                color: AppColors.primaryColor,
              ),
            ),
            color: Colors.white,
          ),
        ],
      ),
      width: double.infinity,
      height: 50.0,
      decoration: BoxDecoration(
          border: Border(top: BorderSide(color: AppColors.greyColor2, width: 0.5)),
          color: Colors.white),
    );
  }

  Widget buildListMessage() {
    getWidgetMessages(listMessage) {
      return ListView.builder(
        padding: EdgeInsets.all(10.0),
        itemBuilder: (context, index) => buildItem(index, listMessage[index]),
        itemCount: listMessage.length,
        reverse: true,
        controller: listScrollController,
      );
    }

    if (listMessage != null && listMessage!.isNotEmpty) {
      return Flexible(child: getWidgetMessages(listMessage));
    }

    return Flexible(
      child: StreamBuilder(
        stream: getAllItems().asStream(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(
                child: CircularProgressIndicator(
                    valueColor: AlwaysStoppedAnimation<Color>(AppColors.themeColor)));
          } else {
            listMessage = snapshot.data as List<CubeMessage>;
            return getWidgetMessages(listMessage);
          }
        },
      ),
    );
  }

  Future<List<CubeMessage>> getAllItems() async {
    Completer<List<CubeMessage>> completer = Completer();
    List<CubeMessage>? messages;
    var params = GetMessagesParameters();
    params.sorter = RequestSorter('desc', '', 'date_sent');
    try {
      await Future.wait<void>([
        getMessages(widget.cubeDialog.dialogId!, params.getRequestParameters())
            .then((result) => messages = result!.items),
        getAllUsersByIds(widget.cubeDialog.occupantsIds!.toSet()).then((result) => _occupants
            .addAll(Map.fromIterable(result!.items, key: (item) => item.id, value: (item) => item)))
      ]);
      completer.complete(messages);
    } catch (error) {
      completer.completeError(error);
    }
    return completer.future;
  }

  Future<bool> onBackPress() {
    // Navigator.pushNamedAndRemoveUntil(context, 'select_dialog', (r) => false,
    //     arguments: {USER_ARG_NAME:widget.cubeUser});
    Navigator.pushAndRemoveUntil(
      context,
      MaterialPageRoute(builder: (context) => ChatList()),
      (route) => false,
    );

    return Future.value(false);
  }

  _initChatListeners() {
    msgSubscription = CubeChatConnection.instance.chatMessagesManager!.chatMessagesStream
        .listen(onReceiveMessage);
    deliveredSubscription = CubeChatConnection.instance.messagesStatusesManager!.deliveredStream
        .listen(onDeliveredMessage);
    readSubscription =
        CubeChatConnection.instance.messagesStatusesManager!.readStream.listen(onReadMessage);
    typingSubscription =
        CubeChatConnection.instance.typingStatusesManager!.isTypingStream.listen(onTypingMessage);
  }

  void _initCubeChat() {
    log("_initCubeChat");
    if (CubeChatConnection.instance.isAuthenticated()) {
      log("[_initCubeChat] isAuthenticated");
      _initChatListeners();
    } else {
      log("[_initCubeChat] not authenticated");
      CubeChatConnection.instance.connectionStateStream.listen((state) {
        log("[_initCubeChat] state $state");
        if (CubeChatConnectionState.Ready == state) {
          _initChatListeners();

          if (_unreadMessages.isNotEmpty) {
            _unreadMessages.forEach((cubeMessage) {
              widget.cubeDialog.readMessage(cubeMessage);
            });
            _unreadMessages.clear();
          }

          if (_unsentMessages.isNotEmpty) {
            _unsentMessages.forEach((cubeMessage) {
              widget.cubeDialog.sendMessage(cubeMessage);
            });

            _unsentMessages.clear();
          }
        }
      });
    }
  }
}

**Comment by saimohanayinam** [comment]
[fluttercode.txt](https://github.com/ConnectyCube/connectycube-web-samples/files/9226757/fluttercode.txt)
[reacrjs code.txt](https://github.com/ConnectyCube/connectycube-web-samples/files/9226759/reacrjs.code.txt)
there are the react js and flutter codes

**Comment by TatankaConCube** [comment]
@saimohanayinam  as I predicted before, you  send attachments in a different way for both platforms
```dart
  void onSendChatAttachment(CubeFile cubeFile, imageData) async {
    final attachment = CubeAttachment();
    attachment.id = cubeFile.uid;
    attachment.type = CubeAttachmentType.IMAGE_TYPE;
    attachment.url = cubeFile.getPublicUrl();
    attachment.height = imageData.height;
    attachment.width = imageData.width;
    final message = createCubeMsg();
    message.body = "Attachment";
    message.attachments = [attachment];
    onSendMessage(message);
  }
```
and JS
```js
  const prepareMessageWithAttachmentAndSend = (file) => {
    const message = {
      type: chosenDialog.type === 3 ? "chat" : "groupchat",
      body: "attachment",
      extension: {
        save_to_history: 1,
        dialog_id: chosenDialog._id,
        attachments: [{ uid: file.uid, id: file.id, type: "photo" }],
      },
    };

    // send the message
    if (chosenDialog.type === 2) {
      message.id = ConnectyCube.chat.send(chosenDialog._id, message);
    } else {
      const opponentId = chosenDialog.occupants_ids.filter(
        (e) => e !== parseInt(localStorage.userId)
      );

      message.id = ConnectyCube.chat.send(opponentId, message);
      const fileUID = message.extension.attachments[0].uid;
      const fileUrl = ConnectyCube.storage.privateUrl(fileUID);
      message.extension.date_sent = parseInt(new Date().getTime() / 1000);
    }

    let img =
      messagesRef.current[chosenDialog._id][
        messagesRef.current[chosenDialog._id].length - 1
      ];
    img._id = message.id;

    setMessages({ ...messagesRef.current });
    debugger;
  };
```

pay attention to the `attachment` object structure:
flutter:
```dart
final attachment = CubeAttachment();
attachment.id = cubeFile.uid;
attachment.type = CubeAttachmentType.IMAGE_TYPE;
attachment.url = cubeFile.getPublicUrl();
attachment.height = imageData.height;
attachment.width = imageData.width;
```
and JS:
```js
{ uid: file.uid, id: file.id, type: "photo" }
```

you should select the preferred platform an other adapt to it
