### ISSUE TITLE
videochat issue

### ISSUE THREAD

**Issue by Dhanunjay2127** [ConnectyCube/connectycube-web-samples#213]
const sessionType = ConnectyCube.videochat.CallType.VIDEO;   

the above line is throwing an error but i take this line of code from the document only 

Error-----
PS D:\xmpp> node webrtc.js
D:\xmpp\webrtc.js:30
const sessionType = ConnectyCube.videochat.CallType.VIDEO; 
                                           ^

TypeError: Cannot read properties of null (reading 'CallType')

**Comment by DaveLomber** [comment]
It could be related to the thing where you forgot to call `ConnectyCube.init` before this
