### ISSUE TITLE
React Native Video Chat setRemoteSessionDescription

### ISSUE THREAD

**Issue by szymonzalarski98** [ConnectyCube/connectycube-web-samples#23]
Hello,

I'm developing a video chat application.
I'm testing my application on two real devices iPhone 7 and Huawei P9.
My app provides video calling and the user can see the caller's video and a video preview (local stream).

In the android device, I cannot see the local stream, but on the iPhone, I get this error:
![IMG_3045](https://user-images.githubusercontent.com/31442502/82742203-42693f80-9d5b-11ea-9fdb-b04908a7fb05.PNG)

**Comment by banshiAnton** [comment]
Hello @szymonzalarski98  , thank for report we will investigate this issue.

**Comment by masmerino13** [comment]
I'm having the same issue on ReacJS, SDK 2.1.7, any update around that?

I have used the same SDK in React Native and VueJS without problems, not sure what's going on with my ReactJS app

@banshiAnton

**Comment by masmerino13** [comment]
Hey, I was doing wrong, I was including the caller id in the `createNewSession` I have removed that and everything is working well now

**Comment by meosieudang** [comment]
same the issue, any fix it?
