### ISSUE TITLE
session.mute('audio') doesn't work after changing audio device with "callSession.switchMediaTracks()"

### ISSUE THREAD

**Issue by kasra-pak** [ConnectyCube/connectycube-web-samples#281]
I'm using the code snippet below to switch my media devices (mic, camera, etc.) in a video call.
the problem is that after running the code below, callSession.mute('audio') wouldn't work properly and user won't be able to mute media devices anymore.

```
const constraints = { [mediaType]: selectedMedia?.id };
callSession.mediaParams.elementId = localStreamVideoRef?.current?.id;

callSession
  .switchMediaTracks(constraints)
  .then((stream: any) => {})
  .catch((error: any) => {});
```

**Comment by ccvlad** [comment]
@kasra-pak 
No need to do `callSession.mediaParams.elementId = localStreamVideoRef?.current?.id`

Please check our videochat sample:
https://github.com/ConnectyCube/connectycube-web-samples/blob/master/videochat/src/call-service.js#L572
There is an example of how to switch video, but everything is the same for audio:
```javascript
const audioDevices = await ConnectyCube.videochat.getMediaDevices("audioinput");
const newStream = await callSession.switchMediaTracks({ audio: videoDevicesId });
```
After testing this sample, it was not possible to detect a similar issue.
