### ISSUE TITLE
Guest user browser issues

### ISSUE THREAD

**Issue by Heisenberg1986** [ConnectyCube/connectycube-web-samples#284]
Hi all i've start my project form web browser vanilla sample, but i have issues with a guest user.
I can get session with ConnectyCube.createSession(user)  with params {"guest":1, "full_name":"Test User"} but the session not return the user part like in the documentation and after in this part ConnectyCube.chat.connect({ userId: user.id, password: user.password })) what parameters i must use for guest user? thanks in advance

**Comment by ccvlad** [comment]
Hi, @Heisenberg1986 

```javascript
const session = await ConnectyCubeInst.createSession({ guest: '1' });
console.log(session);
```
result:
<img width="560" alt="image" src="https://github.com/user-attachments/assets/baf801f4-cbcd-4584-ae0b-49f1c05a6360">

You can use `session.user_id` or `session.user.id` as `userId` and `session.token` as `password` (https://developers.connectycube.com/js/messaging/#connect-to-chat-using-custom-authentication-providers)

Check the code-sample:
```javascript
const session = await ConnectyCubeInst.createSession({ guest: '1' });

await ConnectyCube.chat.connect({
  userId: session.user_id,
  password: session.token
});
```
