### ISSUE TITLE
Help me to integrate

### ISSUE THREAD

**Issue by angelinemeenutech** [ConnectyCube/connectycube-web-samples#43]
Hi,

Can you help me to integrate this in heroku

**Comment by banshiAnton** [comment]
Hi @angelinemeenutech you can use this guide https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-static
Or create create simple node js express server and serve your public folder https://devcenter.heroku.com/articles/getting-started-with-nodejs

**Comment by angelinemeenutech** [comment]
Im already created with static node js i need how i integrate video chat script on that

**Comment by angelinemeenutech** [comment]
https://whispering-savannah-67627.herokuapp.com/

**Comment by banshiAnton** [comment]
Do you user our video-chat sample https://github.com/ConnectyCube/connectycube-web-samples/tree/master/videochat

**Comment by ccvlad** [comment]
Closed due inactivity
