### ISSUE TITLE
Logging in via External identity with JavaScript

### ISSUE THREAD

**Issue by rknobben** [ConnectyCube/connectycube-web-samples#44]
Hi there

Do you have a JS example of logging in a user using Authentication via external identity provider?

Can this all be achieved in JS assuming we provide a server API URL to verify a user's id and session token?

In your documentation you say:

The user logins to ConnectyCube with data received from your Backend:
POST https://api.connectycube.com/login
login=IP_user_id
password=IP_token

Can this be done via JS?

Cheers
Rob

**Comment by ccvlad** [comment]
> Hi there
> 
> Do you have a JS example of logging in a user using Authentication via external identity provider?
> 
> Can this all be achieved in JS assuming we provide a server API URL to verify a user's id and session token?
> 
> In your documentation you say:
> 
> The user logins to ConnectyCube with data received from your Backend:
> POST https://api.connectycube.com/login
> login=IP_user_id
> password=IP_token
> 
> Can this be done via JS?
> 
> Cheers
> Rob

Hi, @rknobben 

We provide a guide how setup the CIdP via the Admin panel. No JS example, cause user verification on BE is individual. 
You should specify params, header and url via the ConnectyCube Admin panel for your application.
To do `POST https://api.connectycube.com/login` you have to call `ConnectyCube.login(thereYourParams)`

**Comment by rknobben** [comment]
Hi support

I have set up CIdP in the Admin

![image](https://user-images.githubusercontent.com/9695304/88742010-f068df80-d138-11ea-903f-42cf48530fd8.png)

And created the API URL on our system (Tested with Postman) but I get this error: POST https://api.connectycube.com/login.json 401 (Unauthorized) when I call  ConnectyCube.login(userCredentials)
  .then((user) => {})
  .catch((error) => {});

![image](https://user-images.githubusercontent.com/9695304/88742410-0d51e280-d13a-11ea-97ad-2f7f4d0ea573.png)

The user credentials are taken from my logged in session
const userCredentials = {
  login: "user7",
  password: "9"
};

where "9" is the session ID for the current session.

I notice from my web server logs that there are no requests to our identity API to even check these credentials.
How can we test that calls to ConnectyCube.login(userCredentials) are triggering your platform to authenticate using
 our API endpoint? 

Cheers
Rob

**Comment by ccvlad** [comment]
Hi, @rknobben 
Seems you need to do [ConnectyCube.init()](https://developers.connectycube.com/js/?id=initialize) and create empty session - [ConnectyCube.createSession()](https://developers.connectycube.com/js/authentication-and-users?id=create-session-token) before request **ConnectyCube.login(...)**
Did you do this before **ConnectyCube.login(...)**?

**Comment by DaveLomber** [comment]
@rknobben seems your custom identity settings are ignore by some reason and the ConnectyCube backend just tries to authenticate user agains ConnectyCube DB and not your DB

Could you please share your app id, we will double check

**Comment by rknobben** [comment]
Hi Dave

App Id: 2881

I don't see the 401 error now... but I also don't see any requests to our identity API endpoint.
Be great if you can check why the custom identity system isn't working.

Also, are there out of the box chat boxes we can launch .. what calls do we need to do that? Or does everything, including the chatbox have to be coded from scratch?


Cheers
Rob

**Comment by rknobben** [comment]
Sorry, I am getting 401's .. just had a filter on my console output for some reason

**Comment by DaveLomber** [comment]
Thanks, checking

re chat boxes - could you please describe more your use case/platform

**Comment by DaveLomber** [comment]
@rknobben could you please try to disable and enable again the CIdP. 
We do not see the flag in storage, I'm afraid it can be some sync issue. 
Let's just disable, save, enable, save and check again

**Comment by rknobben** [comment]
@DaveLomber have disabled, saved, enabled and saved. Still getting 401's unfortunately.

re: chat boxes

I want to pop up something like this (or even simpler):

![image](https://user-images.githubusercontent.com/9695304/88822691-14b9d000-d1bc-11ea-8994-b79a15b26289.png)

Is there anything out of the box to render that on a web page?

**Comment by DaveLomber** [comment]
@rknobben please check https://github.com/ConnectyCube/connectycube-web-samples/tree/master/chat

**Comment by rknobben** [comment]
We have an existing web application (not React) that we want to integrate with. I was hoping that some of ConnectyCube JS libraries opened up simple chat box modals that we could style via CSS and control via the JS.

It sounds like we'd have to extract the relevant code out of the Web React project to work inside our app. That is possible a killer for us as we are time poor needing a vanilla messaging solution we can integrate and style within a week.

Do you have any other solutions?

**Comment by DaveLomber** [comment]
@rknobben appologize I was wrong with my initial statement, your CIdP settings are enabled and should work 

And this is very strange it's returning 401..

Could you please provide 2 things:
1) the complete code snippet you use to login 
2) a response body, if any. Or it's just 401 and empty body? 

Thank you a lot

**Comment by DaveLomber** [comment]
@rknobben also please try the suggestion described here https://github.com/ConnectyCube/connectycube-web-samples/issues/44#issuecomment-665663163

seems it should resolve your issue
