### ISSUE TITLE
Need JS Web Integration Help with Control bar 

### ISSUE THREAD

**Issue by lokesh-jangid** [ConnectyCube/connectycube-web-samples#45]
Hello Support,

We want to use your services for our client portal, APP side it is integrated but on web side stuck, I need your help to integrate this. Can we integrate this Video call with control bar option with ( Video off / on , Switch screen local / remote , Mute , share screen ) etc. Is this also possible chat integrated with video call like google meet. 

Please help us, so we can integrate it successfully.

**Comment by ccvlad** [comment]
Hi, @lokesh-jangid

The Video chat Conference Sample - https://github.com/ConnectyCube/connectycube-web-samples/tree/master/videochat-conf
Here the docs - https://developers.connectycube.com/js/videocalling-conference
Conferencing calls solution (TeaTalk) - https://connectycube.com/teatalk/
You are able to [contact us](https://connectycube.com/contact/) with questions that are not related to code.

**Comment by lokesh-jangid** [comment]
Hi, Hope you check my last message, I have all these demo but I am working with browser JS. I need control bar with browser js. do you have any demo like this please share.

**Comment by ccvlad** [comment]
@lokesh-jangid
All demos for browser in this repo. I've given you links to the sample that you want.

Here is tool/control bar (screen from https://teatalk.connectycube.com/):
<img width="321" alt="Снимок экрана 2020-08-01 в 10 25 52" src="https://user-images.githubusercontent.com/43810932/89096786-e0275d80-d3e1-11ea-9a0d-9527c3775fb4.png">
- a switch on/off mic
- a switch on/off camera
- end a call
- a switch between possible video inputs
- a screen sharing

The "Switch screen local / remote" will be you own implementation. You have all to customize and use the video conference and chat samples.

**Comment by lokesh-jangid** [comment]
Hello Support, 

Audio quality is not good. Noise and Echo problem too much. Could you help me to fix this.  Please help.

**Comment by ccvlad** [comment]
@lokesh-jangid 
Please create new issue if it relates to other theme.

> Hello Support,
> 
> Audio quality is not good. Noise and Echo problem too much. Could you help me to fix this. Please help.

Please describe your problem to help us understand what you mean (steps to reproduce).
Usually the "Noise and Echo problem" appear when you hold devices close to each other in active call state.
