### ISSUE TITLE
Live translation, transcription using Connectycube

### ISSUE THREAD

**Issue by carbonrider** [ConnectyCube/connectycube-web-samples#48]
I am looking for ways to build an online meeting solution wherein people from multiple locations can join it. Each one of them having their own language preference. These users should be able to see the translated text of each speaking user in their own language (basically instant transcription and translation). Any pointers around this requirement will help. 

I looked at [video conferencing documentation](https://developers.connectycube.com/js/videocalling-conference?id=features-supported), but didn't find how to initiate recording for same. The few questions that I have around this requirement are

1. Since each user is speaking in his/her own native language, do I have to subscribe to all the media streams at every user's browser?
2. If all media streams are subscribed, how to decide which video timeslices should be picked from each stream and create the final stream as an output? 
3. How to decide which user is speaking? (This will be required to transcribe only the speaker and then relaying the translation of the same to other users.)

Note that there is also a need to share screen.

**Comment by DaveLomber** [comment]
Hi @carbonrider 

1 - it's already done under the hood. Basically, you have an access to all the participants media stream and can record it if required.

There is `ConnectyCube.videochatconference.onRemoteStreamListener = (session, userId, stream) => {}`, where `userId` is an id of remote participant and `stream` is a media stream of this user

2 - potentially you can store some meta information, depending where a user joined the room, e.g. something like this:

```
const joinedTimes = {}

ConnectyCube.videochatconference.onRemoteStreamListener = (session, userId, stream) => {
   joinedTimes[userId] = Date.now()
}
```

and then use this information as for the proper streams shifting when creating a final stream as an output 

3 - there is an API to get a user's mic level https://developers.connectycube.com/js/videocalling-conference?id=get-remote-user-mic-level . If you check https://teatalk.connectycube.com - we already use it in this demo. the src code is available here https://github.com/ConnectyCube/connectycube-web-samples/tree/master/videochat-conf
