### ISSUE TITLE
Can view camera or hear from web

### ISSUE THREAD

**Issue by SirBertly** [ConnectyCube/connectycube-web-samples#49]
Hi,

Thank you for this fantastic plugin. 

Having installed the mobile sample on my phone and running the web sample online, I'm able to call the mobile app from the web. Upon successful connection, the mobile app user is able to see both cameras and hear both users, however, while the web app user can see themselves, they can neither see nor hear the mobile user.

I recognize that this ticket is close to this one (https://github.com/ConnectyCube/connectycube-reactnative-samples/issues/116), so I run the tests suggested and here are my results below:

![image](https://user-images.githubusercontent.com/149881/90681806-afae4300-e26c-11ea-8f55-0f66b00ef80d.png)

![image](https://user-images.githubusercontent.com/149881/90681984-f69c3880-e26c-11ea-9a7e-100c68a0f0d2.png)

I don't think I did this 👆  right and when I add the servers, nothing happens :-|

**Comment by DaveLomber** [comment]
@SirBertly could you please gather same logs as in first comment 
https://github.com/ConnectyCube/connectycube-reactnative-samples/issues/116#issue-680215395

**Comment by SirBertly** [comment]
Hi, 

We needed to activate our listeners. Thank you.
