### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by AloisBlue** [ConnectyCube/connectycube-web-samples#52]
Hi,

I'm using react with typescript to make a web app that can initiate calls. I'm however having an error while compiling
**Here**
![Screenshot from 2020-09-02 14-46-45](https://user-images.githubusercontent.com/37014066/92071440-5e976680-edb7-11ea-8d19-d9768d17ceda.png)

Below is my **.babelrc**
```
{
  "plugins": [
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ]
  ]
}
```

Any help will be appreciated. Thank you!

**Comment by banshiAnton** [comment]
Hi @AloisBlue, you can find solution in this issue
https://github.com/ConnectyCube/connectycube-js-sdk-releases/issues/44
