### ISSUE TITLE
Integrate API in PHP app

### ISSUE THREAD

**Issue by alxx28** [ConnectyCube/connectycube-web-samples#55]
Hello, we have a web php app related with hospitals and health field, now we need integrate telemedicine and need an api to reach that in our web app(developed with php and javascript-jquery) and need a mobile app and integrare video chat in our web app to ease the communication between a doctor and a patient.

I can´t make that  your samples work.

What sample should I use to develop my solution?

**Comment by DaveLomber** [comment]
As for the web site frontend - we have JS SDK

Here is a guide on how to connect connecctycube.js into web page https://developers.connectycube.com/js/ 

Then, I suggest to follow the Video Calling guide https://developers.connectycube.com/js/videocalling and also use the ode sample as for the reference 

Please let us know what exit issues u have with it

**Comment by alxx28** [comment]
It would be important samples with pure javascript.

**Comment by DaveLomber** [comment]
https://developers.connectycube.com/js/code-samples

both P2P calling and Conference calling are in pure JS

For chat we use React
