### ISSUE TITLE
Difficult to create a dialog

### ISSUE THREAD

**Issue by alxx28** [ConnectyCube/connectycube-web-samples#57]
Hello, I am trying to create a dialog following the docs.

`function chat() {
            const userCredentials = {
                userId: 2132688,
                password: 'xxxxxxxxx'
            };

            ConnectyCube.chat.connect(userCredentials).then(() => {
                console.log('User Connected');

                const params = {
                    type: 1,
                    occupants_ids: [2132688]
                };

                ConnectyCube.chat.dialog.create(params).then(dialog => {
                    console.log('Dialog Created');
                }).catch(error => {

                });

            }).catch(error => {
                console.log('User Not Connected');
            });
        }`

But I am getting the following error and I don't know the meaning of that error.

{"errors":{"base":["Forbidden. Need user."]}}

**Comment by ccvlad** [comment]
Hi, @alxx28 
First of all you need to do `ConnectyCube.init(appCredentials, appConfig)`, then you should create session `ConnectyCube.createSession(userCredentials)` or `ConnectyCube.createSession()` + `ConnectyCube.login(userCredentials)`.

Check:
- Create session (can be empty or with user) - https://developers.connectycube.com/js/authentication-and-users?id=session-token-rights
- Create new user (sign-up if you need)- https://developers.connectycube.com/js/authentication-and-users?id=user-signup

**Comment by alxx28** [comment]
This is my source code, Sign-up users already works, I added create session, but I get the same message.

`const CREDENTIALS = {
            appId: 3318,
            authKey: "xxxx",
            authSecret: "xxxxxxxx"
        };

        ConnectyCube.init(CREDENTIALS);

        ConnectyCube.createSession().then((session) => {

        }).catch((error) => {

        });

        function signup_user() {
            var user = 'P001' ;
            var password = '12345678';

            const userProfile = {
                login: user,
                password: password,
                full_name: $('#txt_name').val()
            };

            ConnectyCube.users.signup(userProfile).then((data) => {
                alert('ok=>' + data.user.id);
            }).catch((error) => {
                alert(error[0]);
            });
        }

        function chat() {
            const userCredentials = {
                userId: 2132688,
                password: '7f9f7d785'
            };
            
            ConnectyCube.createSession(userCredentials).then((session) => {
                console.log('Created session');
                
                ConnectyCube.chat.connect(userCredentials).then(() => {
                    console.log('User Connected');
                    const params = {
                        type: 1,
                        occupants_ids: [2132688]
                    };

                    ConnectyCube.chat.dialog.create(params).then(dialog => {
                        console.log('Dialog Created');
                    }).catch(error => {

                    });

                }).catch(error => {
                    console.log('User Not Connected');
                });
            }).catch((error) => {

            });
        }

        ConnectyCube.chat.onDisconnectedListener = onDisconnectedListener;
        function onDisconnectedListener() {
            console.log('Disconnected');
        }

        $('#dv_videocall').dialog({
            autoOpen: false,
            resizable: false,
            height: 400,
            width: 970,
            modal: true,
            buttons: {
                Registrar: function () {
                    signup_user();
                },
                Chat: function () {
                    chat();
                },
                Salir: function () {
                    $(this).dialog('close');
                }
            },
            close: function () {
                ConnectyCube.chat.disconnect();
            }
        });`

**Comment by alxx28** [comment]
I added what you suggested me, Sign Up users is working fine,but I am getting the following error:
{"errors":["You do not have appropriate permissions. Broadcast dialogs can be created only via Admin panel."]}

Here is my source code:

`const CREDENTIALS = {
            appId: 3318,
            authKey: "xxxxx-",
            authSecret: "xxxxxx"
        };

        ConnectyCube.init(CREDENTIALS);

        ConnectyCube.createSession().then((session) => {

        }).catch((error) => {

        });

        function signup_user() {
            var usuario = 'P' + $('#hd_idusr').val();
            var password = '12345678';
            var correo = $('#hd_correo').val();
            correo = correo ? correo : usuario + '@correo.com';

            const userProfile = {
                login: usuario,
                password: password,
                full_name: $('#txt_nombres').val(),
                email: correo
            };

            ConnectyCube.users.signup(userProfile).then((data) => {
                alert('ok=>' + data.user.id);
            }).catch((error) => {
                alert(error[0]);
            });
        }

        function chat() {
            const userCredentials = {
                login: 'S5',
                password: '7f9f7d785'
            };

            ConnectyCube.createSession(userCredentials).then((session) => {
                console.log('Created session');

                ConnectyCube.login(userCredentials).then((user) => {
                    console.log('user login succesful');
                    var userCredentialss = {
                        userId: 2141131,
                        password: '7f9f7d785'
                    };

                    ConnectyCube.chat.connect(userCredentialss).then(() => {
                        console.log('User Connected to chat');

                        const params = {
                            type: 1,
                            occupants_ids: [2141131]
                        };
                        ConnectyCube.chat.dialog.create(params).then(dialog => {
                            console.log('Dialog Created');
                        }).catch(error => {

                        });

                    });

                }).catch((error) => {

                });
            }).catch((error) => {

            });
        }

        ConnectyCube.chat.onDisconnectedListener = onDisconnectedListener;
        function onDisconnectedListener() {
            console.log('Disconnected');
        }

        $('#dv_videocall').dialog({
            autoOpen: false,
            resizable: false,
            height: 400,
            width: 970,
            modal: true,
            buttons: {
                Sign Up: function () {
                    signup_user();
                },
                Chat: function () {
                    chat();
                },
                Salir: function () {
                    $(this).dialog('close');
                }
            },
            close: function () {
                ConnectyCube.chat.disconnect();
            }
        });`

**Comment by ccvlad** [comment]
A `type` field in a dialog model:
https://developers.connectycube.com/server/chat?id=chat-dialog-model
Check roles and privileges for each dialog's type:
https://developers.connectycube.com/server/chat?id=roles-and-privileges

**Comment by ccvlad** [comment]
@alxx28 

> A `type` field in a dialog model:
> https://developers.connectycube.com/server/chat?id=chat-dialog-model
> Check roles and privileges for each dialog's type:
> https://developers.connectycube.com/server/chat?id=roles-and-privileges

Was it helpful? Please close the issue if you managed to solve you issue.
