### ISSUE TITLE
Who is userId on sendmessage

### ISSUE THREAD

**Issue by alxx28** [ConnectyCube/connectycube-web-samples#59]
In this fragment who is userId?, who sends or receives a message.

function onMessage(userId, message) {
    console.log('[ConnectyCube.chat.onMessageListener] callback:', userId, message)
}

**Comment by ccvlad** [comment]
@alxx28 
https://developers.connectycube.com/js/messaging?id=sendreceive-chat-messages

`ConnectyCube.chat.onMessageListener = onMessage;` - here you receive messages from users.
You are also able to receive message from yourself in this listener (if groupchat).
You will get  a `message` with `userId`, who sent the `message`.
