### ISSUE TITLE
Nothing happen when use ConnectyCube.chat.send(dialog_id, message) for public chat

### ISSUE THREAD

**Issue by ahmadsaufiyuddin-roomie** [ConnectyCube/connectycube-web-samples#64]
has anyone meet this problem?

i make a public chat, already subscribe and follow all the step.

but when try to send message using ConnectyCube.chat.send(dialog_id, message), nothing happen, it just return id.

if i use, axios to send message to the public chat using server api, it's working fine

**Comment by ccvlad** [comment]
Hi, @ahmadsaufiyuddin-roomie 

Chat works on XMPP protocol to send and receive data in real-time.
You should setup listener for incoming messages.

Check our docs how to [send/receive messages](https://developers.connectycube.com/js/messaging?id=sendreceive-chat-messages).

**Comment by ahmadsaufiyuddin-roomie** [comment]
i already set listener, but nothing happen. when i check in admin.connectycube, there no message in related dialog

**Comment by ccvlad** [comment]
Show your logs

**Comment by ahmadsaufiyuddin-roomie** [comment]
`setTimeout(function(){
		ConnectyCube.setSession(CUBE.session);

		setTimeout(function(){
			var CubeChatCredentials = {
				userId: RENO.user.connectycube_id,
				password: RENO.secret,
			};

			ConnectyCube.chat.connect(CubeChatCredentials)
			.then(() => {
				ConnectyCube.chat.dialog
					.subscribeToPublic(RENO.user.connectycube_dialog_id)
					.then((dialog) => {
						ConnectyCube.chat.muc.join(dialog._id).catch(error => {
							for(var key in error){
								console.log('join chat error: '+key+': '+error[key]);
							}
						});
					})
					.catch((error) => {});

				ConnectyCube.chat.onMessageListener = onMessage;
				ConnectyCube.chat.onDisconnectedListener = onDisconnectedListener;
				ConnectyCube.chat.onReconnectListener = onReconnectListener;
			})
			.catch((error) => {
				for(var key in error){
					console.log('connect chat error: '+key+': '+error[key]);
				}
			});
		}, 2000);
	}, 2000);`



`$('#test-send').on('click', function(){
	const message = {
		type: 'groupchat',
		body: "How are you today?",
		extension: {
			save_to_history: 1,
			dialog_id: RENO.user.connectycube_dialog_id
		},
		markable: 1
	};

	message.id = ConnectyCube.chat.send(RENO.user.connectycube_dialog_id, message);
	console.log('test-send ', message.id);
});

function onMessage(userId, message) {
	console.log("[ConnectyCube.chat.onMessageListener] callback:", userId, message);
}

function onDisconnectedListener() {
	console.log("[ConnectyCube.chat.onDisconnectedListener] callback:");
}
function onReconnectListener() {
	console.log("[ConnectyCube.chat.onReconnectListener] callback:");
}`

currently i just make when you click '#test-send', then send message

on console when click 'test-send  5fa5280b356a740161000000'

thats all, chat didnt go in the dialog, even when i login other user, didnt get the onmessagelistener callback, which they receive if i send use postman

**Comment by ahmadsaufiyuddin-roomie** [comment]
anyone can help on this?

**Comment by ahmadsaufiyuddin-roomie** [comment]
![Uploading Screenshot 2020-11-10 at 11.25.28 AM.png…]()

**Comment by ahmadsaufiyuddin-roomie** [comment]
![Screenshot 2020-11-10 at 11 25 28 AM](https://user-images.githubusercontent.com/67673998/98623893-97b7fe00-2347-11eb-8581-36864e77f7ba.png)
![Screenshot 2020-11-10 at 11 24 28 AM](https://user-images.githubusercontent.com/67673998/98623900-9be41b80-2347-11eb-88e9-09b15bf039f1.png)

**Comment by ahmadsaufiyuddin-roomie** [comment]
@ccvlad my log

**Comment by ccvlad** [comment]
@ahmadsaufiyuddin-roomie 

What dialog's type with id = _"5fa3d0acca8bf40e30066dff"_ ? I mean that not each user is able to write to dialog with type = 1 (broadcast), only Super admin (owner of admin panel).

- [Dialogs](https://developers.connectycube.com/js/messaging?id=dialogs)
- [Roles and priveleges](https://developers.connectycube.com/server/chat?id=roles-and-privileges)

**Comment by ahmadsaufiyuddin-roomie** [comment]
@ccvlad 
its public chat

**Comment by ahmadsaufiyuddin-roomie** [comment]
![Screenshot 2020-11-10 at 5 41 34 PM](https://user-images.githubusercontent.com/67673998/98656810-0fa01b80-237c-11eb-88ea-50ea26171e79.png)

**Comment by ahmadsaufiyuddin-roomie** [comment]
i use server api to send message, no problem with it

**Comment by ccvlad** [comment]
Is sender a super admin? Other roles do not have privileges to send messages in public chat.

**Comment by ccvlad** [comment]
Please check is exist the dialog with ID = "5fa3d0acca8bf40e30066dff" ? 

```javascript
ConnectyCube.chat.dialog.list({_id:  '5fa3d0acca8bf40e30066dff'})
  .then(({items}) => {
    console.log('dialogs list:', items)
  })
  .catch(error => {
    console.log('error:', error);
  });
```

FYI. If last subscriber unsubscribes from `public channel`, the dialog will delete from server. Use `ConnectyCube.chat.muc.leave(publicDialogId)` instead to prevent listen to messages.

**Comment by ahmadsaufiyuddin-roomie** [comment]
@ccvlad the sender is not super admin, and success to send message in public chat using server api

and dialog with id = 5fa3d0acca8bf40e30066dff exist in server

yet cannot send message using ConnectyCube.chat.send(dialog_id, message)

**Comment by ccvlad** [comment]
Try the code below and use `dialog.xmpp_room_jid` instead of `dialog._id` to send message:
```javascript
const onMessage = (userId, message) => {
  console.log("[ConnectyCube.chat.onMessageListener] callback:", userId, message);
};

const newDialogParams = {
  type: 4,
  name: 'Some public channel',
  description: '<some description>'
};

const sendMessage = (dialog, text) => {
  const message = {
    type: dialog.type === 3 ? 'chat' : 'groupchat',
    body: text,
    extension: {
      save_to_history: 1,
      dialog_id: dialog._id
    },
    markable: 1
  };
  const recipient = dialog.type === 3 ? userIdToSend : dialog.xmpp_room_jid; // use `dialog.xmpp_room_jid` for dialog's type 1, 2 and 4, user_id for type = 3 (1-1 chat)

  ConnectyCube.chat.send(recipient, message);
};

ConnectyCube.chat.connect(CubeChatCredentials)
  .then(async () => {
    ...
    ConnectyCube.chat.onMessageListener = onMessage;
    const dialog = await ConnectyCube.chat.dialog.create(newDialogParams);
    await ConnectyCube.chat.dialog.subscribeToPublic(dialog.id)
    sendMessage();
  })
  .catch((error) => {
    console.error('error', error);
  });
```

**Comment by ahmadsaufiyuddin-roomie** [comment]
@ccvlad thankss!! your code works. i succeed to send message using dialog.xmpp_room_jid
