### ISSUE TITLE
Uncaught DOMException: This track is already set on a sender. connectycube.min.js:1

### ISSUE THREAD

**Issue by alxx28** [ConnectyCube/connectycube-web-samples#66]
The video calling sometimes works, sometimes not, I don 't know what is the meaning of "Uncaught DOMException: This track is already set on a sender. connectycube.min.js:1", so that I can not solve it and in the web I don't find any solution. This happended after I closed the browser, after this the video calling stopped of working.

**Mozilla**
![error](https://user-images.githubusercontent.com/3847133/98875005-54de4f00-2449-11eb-872f-ed2109513401.jpg)

**Chrome**
![errrror](https://user-images.githubusercontent.com/3847133/98875010-56a81280-2449-11eb-833a-278af944e852.jpg)

Thank you for your help.

**Comment by DaveLomber** [comment]
@alxx28 could you please provide more detailed steps to reproduce it

Especially more details about "This happended after I closed the browser".

It will help us to identify the rot cause and help you 

Thank you

**Comment by alxx28** [comment]
Hello, happened the following. I was testing the videocalling between a laptop and a cellphone, all in web enviroment, then a annoying noise was listened and so that I close the browser in my laptop, but I do not have implemented all details like destroySession and stop the camera and the video when the page is closed, I imagine is that the problem.

That is all, now I have the following code when the browser is closed.

```
$(window).bind('beforeunload', function () {
                        if (ConnectyCube.chat.isConnected) {
                            ConnectyCube.chat.disconnect();
                            ConnectyCube.logout().catch((error) => {
                                console.log('logout=>' + JSON.stringify(error));
                            });
                        }
                        ConnectyCube.destroySession().catch((error) => {
                            console.log('destroySession=>' + JSON.stringify(error));
                        });
                    });
```

And the following is to stop the camera and microphone, but I don't know how to bind it to above event, when the browser is closed.

```
function finishCall(e){                        
                        const extension = {};
                        e.data.x.stop(extension);
                        
                        var videoElem1 = document.getElementById('vd_video11'),
                                    stream1 = videoElem1.srcObject;
                            if (stream1 != null) {
                                var tracks = stream1.getTracks();
                                tracks.forEach(function (track) {
                                    track.stop();
                                });
                                videoElem1.srcObject = null;
                            }

                            var videoElem2 = document.getElementById('vd_video22'),
                                    stream2 = videoElem2.srcObject;
                            if (stream2 != null) {
                                var tracks = stream2.getTracks();
                                tracks.forEach(function (track) {
                                    track.stop();
                                });
                                videoElem2.srcObject = null;
                            }
                    }
```

**Comment by alxx28** [comment]
Hello, I found the real problem, el problem is that the videocalling only works when the Initiator_id is 2192643 and the Oppnent_id is 2146781, when I change any of these, the videocalling does not work anymore, I suppose the problem is when I am trying to close all communication channel, and something is wrong in my code.

**Initiator**
const CREDENTIALS = {
            appId: xxxx,
            authKey: 'xxxxxx-',
            authSecret: 'xxxxxxx'
        };

        ConnectyCube.init(CREDENTIALS);

        function signup_user() {
            var login = 'P' + $('#hd_idusr').val();
            /*Buscar si existe usuario registrado en la API*/
            ConnectyCube.users.get({login: login}).then((result) => {
                console.log('User Exists:' + result.user.id);
                chat();
            }).catch((error) => {
                //alert('User not exists ['+JSON.stringify(error)+']');
                console.log('User not exists [' + error.info.message + ']');
                var password = $('#txt_fecnacimiento').val().replace(/-/g, '') + '*';
                var correo = $('#hd_correo').val();
                correo = correo ? correo : login + '@correo.com';

                const userProfile = {
                    login: login,
                    password: password,
                    full_name: $('#txt_nombres').val(),
                    email: correo
                };

                ConnectyCube.users.signup(userProfile).then((data) => {
                    console.log('ok=>' + data.user.id);
                    chat();
                }).catch((error) => {
                    console.log(JSON.stringify(error));
                });
            });
        }

        function chat() {
            /*Buscar Id del Paciente para crear el dialogo*/
            var login_paciente = 'P' + $('#hd_idusr').val();
            ConnectyCube.users.get({login: login_paciente}).then((result) => {
                var id_paciente = result.user.id;
                $('#hd_idpaciente').val(id_paciente);
                /*Login Medico*/
                const userCredentials = {
                    login: 'S' + $('#txt_profatiende').attr('data-id-usuario'),
                    password: $('#txt_profatiende').attr('data-psw')
                };

                ConnectyCube.createSession(userCredentials).then((session) => {
                    console.log(JSON.stringify(session));
                    console.log('Medic Created session');

                    ConnectyCube.login(userCredentials).then((user) => {
                        var id_profesional = user.id;
                        console.log('Medic login succesful=>' + id_profesional);
                        $('#hd_idprofesional').val(id_profesional);
                        const chatCredentials = {
                            userId: id_profesional,
                            password: $('#txt_profatiende').attr('data-psw')
                        };

                        ConnectyCube.chat.connect(chatCredentials).then(() => {
                            console.log('Medic Connected to chat');
                            console.log('Id Paciente:' + id_paciente);

                            const dialogParams = {
                                type: 3,
                                occupants_ids: [id_paciente]
                            };

                            ConnectyCube.chat.dialog.create(dialogParams).then(dialog => {
                                console.log(JSON.stringify(dialog));
                                console.log('Dialog Created:' + dialog._id);
                                $('#hd_iddialog').val(dialog._id);
                            }).catch(error => {
                                console.log(JSON.stringify(error));
                            });
                        }).catch((error) => {
                            console.log(JSON.stringify(error));
                        });

                    }).catch((error) => {
                        console.log(JSON.stringify(error));
                    });

                }).catch((error) => {
                    console.log(JSON.stringify(error));
                });
                /*Fin Login Medico*/
            }).catch((error) => {
                console.log(JSON.stringify(error));
            });
        }

        ConnectyCube.chat.onMessageListener = onMessage;

        function onMessage(userId, message) {
            console.log('[ConnectyCube.chat.onMessageListener] callback:', userId, message);
            var dv_message = $('#dv_mensajeschat');
            dv_message.append('<div><b>Paciente:</b>' + message.body + '</div>');
            dv_message.scrollTop(dv_message[0].scrollHeight);
        }

        ConnectyCube.chat.onMessageTypingListener = function (isTyping, userId, dialogId) {
            console.log("[ConnectyCube.chat.onMessageTypingListener] callback:", isTyping, userId, dialogId);
        };

        function sendMessage() {
            ConnectyCube.chat.sendIsStopTypingStatus($('#hd_idpaciente').val());
            var mensaje = $('#dv_areamensaje').html();
            const message = {
                type: 'chat',
                body: mensaje,
                extension: {
                    save_to_history: 1,
                    dialog_id: $('#hd_iddialog').val()
                },
                markable: 1
            };
            message.id = ConnectyCube.chat.send($('#hd_idpaciente').val(), message);
            var dv_message = $('#dv_mensajeschat');
            dv_message.append('<div><b>Yo:</b>' + mensaje + '</div>');
            dv_message.scrollTop(dv_message[0].scrollHeight);
            $('#dv_areamensaje').html('');
        }

        $('#dv_areamensaje').keypress(function (e) {
            ConnectyCube.chat.sendIsTypingStatus($('#hd_idpaciente').val());
            setTimeout(function () {
                ConnectyCube.chat.sendIsStopTypingStatus($('#hd_idpaciente').val());
            }, 1000);
            if (e.keyCode == 13) {
                sendMessage();
                return false;
            }
        });

        function startVideo() {
            const calleesIds = [$('#hd_idprofesional').val(), $('#hd_idpaciente').val()]; /*User's ids*/
            const sessionType = ConnectyCube.videochat.CallType.VIDEO;
            const additionalOptions = {};
            const session = ConnectyCube.videochat.createNewSession(calleesIds, sessionType, additionalOptions);
            //console.log(session);

            const mediaParams = {
                audio: true,
                video: true,
                options: {
                    muted: true,
                    mirror: true
                }
            };

            session.getUserMedia(mediaParams).then((localStream) => {
                console.log(JSON.stringify(localStream));
                session.attachMediaStream('vd_video1', localStream);
                const extension = {};
                session.call(extension, (error) => {

                });
                $('#btn_finalizarvd').on('click', {x: session}, finishCall);
            }).catch((error) => {
                console.log(JSON.stringify(error));
            });
        }

        function finishCall(e) {
            const extension = {};
            e.data.x.stop(extension);
            var videoElem1 = document.getElementById('vd_video1'),
                    stream1 = videoElem1.srcObject;
            if (stream1 != null) {
                var tracks = stream1.getTracks();
                tracks.forEach(function (track) {
                    track.stop();
                });
                videoElem1.srcObject = null;
            }

            var videoElem2 = document.getElementById('vd_video2'),
                    stream2 = videoElem2.srcObject;
            if (stream2 != null) {
                var tracks = stream2.getTracks();
                tracks.forEach(function (track) {
                    track.stop();
                });
                videoElem2.srcObject = null;
            }
        }

        ConnectyCube.videochat.onAcceptCallListener = function (session, userId, extension) {
            console.log('Accepted call');
        };

        ConnectyCube.videochat.onRemoteStreamListener = function (session, userID, remoteStream) {
            session.attachMediaStream('vd_video2', remoteStream);
        };

        ConnectyCube.videochat.onStopCallListener = function (session, userId, extension) {
            console.log('Finished Call');
        };

        $('#dv_videollamada').dialog({
            autoOpen: false,
            resizable: false,
            height: 600,
            width: 250,
            modal: false,
            buttons: [
                {
                    text: 'Registrar', click: function () {
                        signup_user();
                    }
                },
                {
                    text: 'Chat', click: function () {
                        chat();
                    }
                },
                {
                    text: 'Enviar', click: function () {
                        sendMessage();
                    }
                },
                {
                    text: 'Video', click: function () {
                        startVideo();
                    }
                },
                {
                    text: 'Salir', click: function () {
                        $(this).dialog('close');
                    }
                }
            ],
            open: function () {

            },
            close: function () {
                $(this).find('input').val('');
                $('#dv_areamensaje').html('');
                $('#dv_mensajeschat').html('');

                if (ConnectyCube.chat.isConnected) {
                    var videoElem1 = document.getElementById('vd_video1'),
                            stream1 = videoElem1.srcObject;
                    if (stream1 != null) {
                        var tracks = stream1.getTracks();
                        tracks.forEach(function (track) {
                            track.stop();
                        });
                        videoElem1.srcObject = null;
                    }

                    var videoElem2 = document.getElementById('vd_video2'),
                            stream2 = videoElem2.srcObject;
                    if (stream2 != null) {
                        var tracks = stream2.getTracks();
                        tracks.forEach(function (track) {
                            track.stop();
                        });
                        videoElem2.srcObject = null;
                    }

                    ConnectyCube.chat.disconnect();
                    ConnectyCube.logout().catch((error) => {
                        console.log('logout=>' + JSON.stringify(error));
                    });
                    ConnectyCube.destroySession().catch((error) => {
                        console.log('destroySession=>' + JSON.stringify(error));
                    });
                }
            }
        });

        $(window).bind('beforeunload', function () {
            if (ConnectyCube.chat.isConnected) {
                $('#btn_finalizarvd').trigger('click');
                ConnectyCube.chat.disconnect();
                ConnectyCube.logout().catch((error) => {
                    console.log('logout=>' + JSON.stringify(error));
                });
                ConnectyCube.destroySession().catch((error) => {
                    console.log('destroySession=>' + JSON.stringify(error));
                });
            }
        });

**Opponent_id**

```
const CREDENTIALS = {
                        appId: 3318,
                        authKey: 'hbDEsgtEADRbu9-',
                        authSecret: 'utZQ4DTvWLa8cuL'
                    };

                    ConnectyCube.init(CREDENTIALS);
                    ConnectyCube.chat.onMessageListener = onMessage;

                    function onMessage(userId, message) {
                        console.log('[ConnectyCube.chat.onMessageListener] callback:', userId, message);
                        console.log(message.body);
                        var dv_message = $('#dv_mensajes');
                        dv_message.attr({'data-id-medico': userId, 'data-id-dialog': message.dialog_id}).append('<div><b>Médico:</b>' + message.body + '</div>');
                        dv_message.scrollTop(dv_message[0].scrollHeight);
                    }

                    function sendMessage() {
                        var id_medico = $('#dv_mensajes').attr('data-id-medico');
                        var id_dialog = $('#dv_mensajes').attr('data-id-dialog');
                        var mensaje = $('#txt_mensaje').html();
                        const message = {
                            type: 'chat',
                            body: mensaje,
                            extension: {
                                save_to_history: 1,
                                dialog_id: id_dialog
                            },
                            markable: 1
                        };
                        message.id = ConnectyCube.chat.send(id_medico, message);
                        var dv_message = $('#dv_mensajes');
                        dv_message.append('<div><b>Yo:</b>' + mensaje + '</div>');
                        dv_message.scrollTop(dv_message[0].scrollHeight);
                        $('#txt_mensaje').html('');
                    }

                    ConnectyCube.chat.onMessageTypingListener = function (isTyping, userId, dialogId) {
                        console.log("[ConnectyCube.chat.onMessageTypingListener] callback:", isTyping, userId, dialogId);
                        if (isTyping) {
                            $('#dv_estaescribiendo').html('Médico está escribiendo....');
                        } else {
                            $('#dv_estaescribiendo').html('');
                        }
                    };

                    ConnectyCube.chat.onSystemMessageListener = function (msg) {
                        console.log(msg);
                    };

                    ConnectyCube.videochat.onCallListener = function (session, extension) {
                        console.log('Session=>' + session);
                        console.log('Session=>' + extension);
                        $('#dv_console').append('Session=>' + session + '<br/>');
                        $('#dv_console').append('Session=>' + JSON.stringify(extension) + '<br/>');
                        $('#dv_console').append('Session=>Some one is calling<br/>');
                        $('#btn_aceptar').on('click', {x: session}, acceptCall);
                        $('#btn_finalizar').on('click', {x: session}, finishCall);
                    };

                    function acceptCall(e) {
                        const mediaParams = {
                            audio: true,
                            video: true,
                            options: {
                                muted: true,
                                mirror: true
                            }
                        };

                        e.data.x.getUserMedia(mediaParams).then((localStream) => {
                            console.log(JSON.stringify(localStream));
                            e.data.x.attachMediaStream('vd_video11', localStream);
                            /*Iniciar la llamada*/
                            console.log('session=>' + e.data.x);
                            const extensionn = {};
                            e.data.x.accept(extensionn);
                        }).catch((error) => {
                            console.log(JSON.stringify(error));
                        });
                    }

                    ConnectyCube.videochat.onUserNotAnswerListener = function (session, userId) {

                    };

                    ConnectyCube.videochat.onAcceptCallListener = function (session, userId, extension) {
                        console.log('Accepted call');
                    };

                    ConnectyCube.videochat.onRemoteStreamListener = function (session, userID, remoteStream) {
                        session.attachMediaStream('vd_video22', remoteStream);
                    };

                    $('#btn_enviar').click(function () {
                        sendMessage();
                    });

                    $('#txt_mensaje').keypress(function () {

                    }).keypress(function (e) {
                        if (e.keyCode == 13) {
                            sendMessage();
                            return false;
                        }
                    });

                    /*url: 'http://localhost/proyecto/Api/getPaciente',*/

                    $('#btn_conectar').click(function () {
                        var num_documento = $('#txt_numdocumento').val();
                        $.ajax({
                            url: 'https://192.168.0.102/proyecto/Api/getPaciente',
                            data: {num_documento: num_documento},
                            type: 'GET',
                            dataType: 'json'
                        }).done(function (data) {
                            var clave = data.fn + '*';
                            var userCredentials = {
                                login: 'P' + data.id,
                                password: clave
                            };

                            ConnectyCube.createSession().then((session) => {
                                console.log('Session started');
                                ConnectyCube.createSession(userCredentials).then((session) => {
                                    console.log(JSON.stringify(session));
                                    console.log('Patient Created session');
                                    ConnectyCube.login(userCredentials).then((user) => {
                                        var id_paciente = user.id;
                                        console.log('Patient login succesful=>' + id_paciente);
                                        var chatCredentials = {
                                            userId: id_paciente,
                                            password: clave
                                        };
                                        ConnectyCube.chat.connect(chatCredentials).then(() => {
                                            $('#dv_console').html('Patient Connected to chat');
                                            console.log('Patient Connected to chat');
                                            console.log('Id Paciente:' + id_paciente);
                                        }).catch((error) => {
                                            console.log(JSON.stringify(error));
                                        });
                                    }).catch((error) => {
                                        console.log(JSON.stringify(error));
                                    });
                                }).catch((error) => {
                                    console.log(JSON.stringify(error));
                                });
                            }).catch((error) => {
                                console.log(JSON.stringify(error));
                            });
                        });
                    });

                    ConnectyCube.videochat.onStopCallListener = function (session, userId, extension) {
                        console.log('Finished Call');
                    };

                    function finishCall(e) {
                        const extension = {};
                        e.data.x.stop(extension);

                        var videoElem1 = document.getElementById('vd_video11'),
                                stream1 = videoElem1.srcObject;
                        if (stream1 != null) {
                            var tracks = stream1.getTracks();
                            tracks.forEach(function (track) {
                                track.stop();
                            });
                            videoElem1.srcObject = null;
                        }

                        var videoElem2 = document.getElementById('vd_video22'),
                                stream2 = videoElem2.srcObject;
                        if (stream2 != null) {
                            var tracks = stream2.getTracks();
                            tracks.forEach(function (track) {
                                track.stop();
                            });
                            videoElem2.srcObject = null;
                        }
                    }

                    $(window).bind('beforeunload', function () {
                        if (ConnectyCube.chat.isConnected) {
                            $('#btn_finalizar').trigger('click');
                            ConnectyCube.chat.disconnect();
                            ConnectyCube.logout().catch((error) => {
                                console.log('logout=>' + JSON.stringify(error));
                            });
                        }
                        ConnectyCube.destroySession().catch((error) => {
                            console.log('destroySession=>' + JSON.stringify(error));
                        });
                    });

```

**Comment by DaveLomber** [comment]
@alxx28 does original code sample work with new users?

**Comment by DaveLomber** [comment]
Basically, 
I analysed your logs, and it seems you have 2 users calling each other at same time or something like this.. 
which leads to double accept call flow and then it raises an error: "This track is already set on a sender"

Could you please do 2 things:
1) make sure you have a clear call flow - one users calls, 2d user accepts the call
2) is still not clear - please provide logs that you shared on 2nd screenshot for both caller and callee. We should found a rot cause there.

Thanks

**Comment by alxx28** [comment]
I changed two new users signed up today and the video calling did not work.

User ids: Initiator_id: 2696330,Opponent_id: 2696378

My flow is the following, the medic is the only person who stablishes the comunnication, he is who starts a Dialog for the chat and who starts a video calling, the patient(Opponent in this case) is who accepts the video calling.

**Initiator**
Mozilla
![M](https://user-images.githubusercontent.com/3847133/99281579-a9dee400-2800-11eb-90b0-12d06f74e267.jpg)

Chrome
![C](https://user-images.githubusercontent.com/3847133/99281625-bcf1b400-2800-11eb-90f8-de4585504530.jpg)


**Opponent**
Mozilla
![M](https://user-images.githubusercontent.com/3847133/99281692-d135b100-2800-11eb-9156-7fe036fe8f8e.jpg)

Chrome
![C](https://user-images.githubusercontent.com/3847133/99281740-deeb3680-2800-11eb-9b85-fae0cca38ff0.jpg)

**Comment by alxx28** [comment]
I delete all users now the video calling absolutely does not work

**Comment by DaveLomber** [comment]
@alxx28 

please do one of the following, for a faster resolution
1) share complete logs on both caller and callee side.
By log I mean these:


from the start till the issue occured

<img width="828" alt="Screenshot 2020-11-20 at 22 49 56" src="https://user-images.githubusercontent.com/39332586/99848613-c2ddf100-2b82-11eb-99e4-e1d7abe6831c.png">

A complete log is required 

2) you can send your demo app src code to support@conectycube.com 
It will be checked and then the tea, will get back to you with a rot cause where the issue is

Please do on the above
thanks

**Comment by alxx28** [comment]
My email service is failing, but here is the files that you need.
[chat-and-logs.zip](https://github.com/ConnectyCube/connectycube-web-samples/files/5583840/chat-and-logs.zip)
