### ISSUE TITLE
Need working sample

### ISSUE THREAD

**Issue by FredmanW** [ConnectyCube/connectycube-web-samples#67]
Hello, 
I followed the steps as best I could as I'm not a professional developer but I know just enough JS, PHP, HTML, and CSS to build things. The .zip file was extracted on my hosted server but I could only get the videochat/dist/index.html to work as a demo and not the videochat-conf/index.html. 

Is the  videochat-conf/index.html basically TeaTalk? If so, are the exact same files used for TeaTalk supposed to be in videochat-conf directory?

Also, with videochat, I was able to change the config.js file with my credentials from my admin app account. Yet as I want to change the input user data for my working sample I see that neither altering the main.map or main.js files to update them with my users content info works. It is as if there is something other than these two files and the config.js that are manipulating how the user content is used. I want to create my own UI layout as a working sample. I made various CSS and JS hacks to do this but hit a wall in other places. Knowing exactly where I can add my user content so that the system recognizes it as legitimate content is needed.

So as advertised. I would like to please receive a working sample (TeaTalk preferably due to needing more than 4 users) with more straightforward and accurate methods of using my own user content. 

Thanks for any assistance in this matter.

**Comment by Kachanov-dev** [comment]
Hi @FredmanW!
You need to do the following steps:
1. Open project videochat-conf
2. Run command `npm install`
3. Then run command `npm run build`
Then you will have a dist folder.

**Comment by FredmanW** [comment]
Hi @Kachanov-dev!
Thanks but the last build had an error that says to talk to the author about it.




[npm-debug.log](https://github.com/ConnectyCube/connectycube-web-samples/files/5548894/npm-debug.log)

**Comment by Kachanov-dev** [comment]
@FredmanW, Could you clone our project and run only it, without your environment?

**Comment by FredmanW** [comment]
@Kachanov-dev, I tried but I really don't know what I'm doing. And I created some repository it seems but it doesn't work. Sorry about my lack of education. I just wanted something simple like I was able to try out from other companies like Vonage and Enablex etc. Only their limitation was a workable UI layout that I could manipulate via CSS and JS and in some cases poor support.  Not sure why in this case for me using ConnectyCube is so difficult. Didn't my npm-debug log help?

**Comment by FredmanW** [comment]
@Kachanov-dev, Could it be possible to just provide me with all the needed folders and files without having to do any build or it doesn't work like that? I mean could I just get the dist/ folder like videochat has?

**Comment by Kachanov-dev** [comment]
@FredmanW 

1. You need to clone our project - "git clone" locally to you.
2. Then you open our "connectycube-web-samples" project, and open the "videochat-conf" folder.
3. Run command `npm install`
4. Then run command `npm run build`
5. Then you will have a dist folder.

There is no need to edit anything in the dist folder, minified files are stored there. 

If you want to change something, you need to make changes in the src folder and then run the command `npm run build`

**Comment by FredmanW** [comment]
@Kachanov-dev 

Same npm error when I do do 'npm run build' for the clone.  So do you or anyone know why I'm getting this error on the build? Or how to fix this on the build? Thanks

**Comment by Kachanov-dev** [comment]
@FredmanW
Please try to update:

1. node - v10.+
2. npm - v6.+

And try to repeat the installation steps

**Comment by FredmanW** [comment]
Thanks, I spoke with my hosting company and they had to manually update 'npm' for me as it produced an error when I updated it. So both 'npm' and 'node' are uptodate.

Next issue is the following ---> Join link address for the "videochat-conf" issue #68

I'm not sure what the next step is to get the correct 'join'  link for the second and subsequent callers. 
The dev in the thread mentioned a proper webserver setup and .htaccess. The file is there and so now I don't know the full steps needed to get the proper 'join'link.

**Comment by FredmanW** [comment]
@Kachanov-dev
Can you please email so we can start a conversation. I really need this to work and I have limited resources. Thank you (els.cfw@gmail.com)
