### ISSUE TITLE
Join link address for the "videochat-conf" issue

### ISSUE THREAD

**Issue by FredmanW** [ConnectyCube/connectycube-web-samples#68]
Hello,

I was able to get the videochat-conf/ to partially work by creating some files from the visible view-source files of the TeaTalk demo. Yet, when it comes to a "join" the link path will obviously not work as it creates a path that requires some join folder.
What exactly is happening here and how could I get it to work for my server file paths?

Thanks

https://englishlearningservices.com/join/NWZiMmEzYzczMzc5NTA1OTZjMDAwMDAwIyN3c3M6Ly9qYW51cy1ldXJvcGUtMS5jb25uZWN0eWN1YmUuY29tOjg5ODk=

**Comment by DaveLomber** [comment]
Video conf sample has 2 modes:
- calling mode
- and TeaTalk mode where join by link is implemented

this config is defined here
so you can change it
https://github.com/ConnectyCube/connectycube-web-samples/blob/master/videochat-conf/src/config.js#L64


we use GUEST_ROOM_ONLY_MODE = true for TeaTalk

The rest of the cose is 100% the same

**Comment by DaveLomber** [comment]
Regarding join folder - there is no any folder in fact

What is required is to properly setup a web server so it should forward all folders requests to same root

For example, here is a config for Apache:

**Comment by DaveLomber** [comment]
https://github.com/ConnectyCube/connectycube-web-samples/blob/master/videochat-conf/.htaccess

**Comment by DaveLomber** [comment]
Same can be done for nginx as well

**Comment by FredmanW** [comment]
Forgive but I don't know what is needed to set up my webserver. Are you saying I just need the .htaccess file and I'm done?
So this is what is there now for the .htaccess file. Should it show "home/englishl/CC5/videochat-conf/dist" instead?
Will that cause it to make a proper link for the next subscriber? Please detail the steps. Thanks

RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.html
# DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION BEGIN
PassengerAppRoot "/home/englishl/CC5/videochat-conf"
PassengerBaseURI "/CC5/videochat-conf"
PassengerNodejs "/home/englishl/nodevenv/CC5/videochat-conf/10/bin/node"
PassengerAppType node
PassengerStartupFile src/index.js
# DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION END

**Comment by DaveLomber** [comment]
@FredmanW what web server are you using?
Apache or nginx?
or what cloud provider?

**Comment by FredmanW** [comment]
@DaveLomber I'm on a shared hosting using Apache

**Comment by FredmanW** [comment]
@DaveLomber
I hope you can still help and you didn't give up on me. :)

**Comment by DaveLomber** [comment]
To be honest 
I'm not sure why the above Passenger configs are required

It's not a node js app, but a simple html static app 

I propose to remove those Passenger configs and see what will happen

**Comment by FredmanW** [comment]
@DaveLomber 
It seems after a build the .htaccess is set as you showed. I still have issues with the 'join' link address. So how am I to get this join to work so I can have my next subscriber in the video chat? You mentioned setting up a webserver. Please outline what I would have to do? And would it be possible to do it on a shared server?
Thanks

**Comment by DaveLomber** [comment]
Where you host currently? what's cloud provider?

**Comment by FredmanW** [comment]
A2 Hosting - using their Swift shared server product

**Comment by DaveLomber** [comment]
Closed as outdated
