### ISSUE TITLE
this.localStream is null

### ISSUE THREAD

**Issue by alxx28** [ConnectyCube/connectycube-web-samples#72]
Your answered me this:

The localStream is cleared after the call is finished:

-either by calling stop or received a stop signal from remote party
-or reject
-or when you was calling someone and nobody answered after timeout.
So, after you finished a call, then localStream is cleared.

And then you have 2 solutions:

#1.(actually a proper one) create a new session for a new call - by calling createNewSession
#2.call 'session.getUserMedia' again on same session so a new stream will be obtained and set. But I did not try this.
So #1 should be a correct solution

Now this is my source code, I think that I am doing exactly what you say at the option 1 using createNewSession , then I really don't know what to do to solve it.,  without a similar example is very difficult to fix this, althought I have tried to understand the samples source code.

```
function startVideo() {
            const calleesIds = [$('#hd_idprofesional').val(), $('#hd_idpaciente').val()]; /*User's ids*/
            const sessionType = ConnectyCube.videochat.CallType.VIDEO;
            const additionalOptions = {};
            const session = ConnectyCube.videochat.createNewSession(calleesIds, sessionType, additionalOptions);
            //console.log(session);

            const mediaParams = {
                audio: true,
                video: true,
                options: {
                    muted: true,
                    mirror: false
                }
            };

            session.getUserMedia(mediaParams).then((localStream) => {
                console.log(JSON.stringify(localStream));
                session.attachMediaStream('vd_video1', localStream);
                /*Iniciar la llamada*/
                const extension = {};
                session.call(extension, (error) => {
                    console.log(JSON.stringify(error));
                });
                $('#btn_finalizarvd').on('click', {x: session}, finishCall);
                $('#btn_mutesound').on('click', {x: session,y:'unmute'}, setSound);
                $('#btn_unmutesound').on('click', {x: session,y:'mute'}, setSound);
                $('#btn_mutevideo').on('click', {x: session,y:'unmute'}, setVideo);
                $('#btn_unmutevideo').on('click', {x: session,y:'mute'}, setVideo);
            }).catch((error) => {
                console.log(JSON.stringify(error));
            });
        }
```

**Comment by alxx28** [comment]
Hello, I have not been able to solve this issue, I really would like your help, you gave two solutions but I don't know how to apply  them in mi case.

**#1.(actually a proper one) create a new session for a new call - by calling createNewSession
#2.call 'session.getUserMedia' again on same session so a new stream will be obtained and set. But I did not try this.
So #1 should be a correct solution**

So that I have decided to show how my web and mobile app work in this video, excuse me for my spoken english.

**url web app:** https://cronhis.xyz
user: admin
password:12345

**video url:**     https://cronhis.xyz/video/video.mkv

**mobile app:**   https://cronhis.xyz/video/apk29122020.apk
Identification numbers for mobile app:
11000000
78000000
40000000

The source code you can see it at last of the script consultaexterna.js at line 10056
https://cronhis.xyz/js/historia/consultaexterna/consultaexterna.js
As you can see I always use  createNewSession in the function startVideo(), then I think my problem is in the function
startVideo() and finishCall(e) where I close the session.

Until now to free the camera and microphone the only thing that I can do is reload the page, then all work normally.

**Comment by ccvlad** [comment]
Hello, @alxx28 !
Sorry for a long response! We will check the information you have provided and give you feedback soon!

**Comment by ccvlad** [comment]
Hi, @alxx28 
I was able to make a call from web app to android app. Also second and next calls worked well, but with errors in console.
Did you manage to fix it?

FYI.
WebRTCSession and ConnectyCube's session isn't the same things. I suggest you to do not call the method `finishSession()` after hung-up an audio/video call (after `session.stop()`).
Do not clean ConnectyCube's session with user (the response from `ConnectyCube.createSession(...)`) if would need to use ConnectyCube API for current user login.
Also keep chat connection (`ConnectyCube.chat.connect(...)`) to always have an ability to receive message/signaling via chat.

**Comment by alxx28** [comment]
Hello.
I did  some corrections that you suggested me, but I can't still solve the problem, I attached a link to a video, so you may be undestand in a better way my problem, I commented the source code to reload the page, and I don't know why there are errors when I am trying to close the connection to free all resources I suppose, when I close the main dialog.

url web app: **https://cronhis.xyz**
user: **admin**
password:**12345**

video url: **[(https://cronhis.xyz/video/video.mkv)]**

mobile app: **[(https://cronhis.xyz/video/apk29122020.apk)]**
Identification numbers for mobile app:
11000000
78000000
40000000

Error when I close the dialog with out refreshing the page:
![Error](https://user-images.githubusercontent.com/3847133/107983003-164db880-6f93-11eb-8aeb-d85eeb7c1913.jpg)

This my function when I close the main Dialog, to free the resouces and start a new video call with a new patient.

```
function finishSession() {
            localStorage.removeItem('session');
            if (ConnectyCube.chat.isConnected) {
                ConnectyCube.chat.disconnect();
                ConnectyCube.logout().catch((error) => {
                    console.log('logout=>' + JSON.stringify(error));
                });
                ConnectyCube.destroySession().catch((error) => {
                    console.log('destroySession=>' + JSON.stringify(error));
                });
            }
        }
```

**Comment by ccvlad** [comment]
Hi, @alxx28 !

`ConnectyCube.logout()` and `ConnectyCube.destroySession()` will logout from ConnectyCube's session and clean session. You won't be able use REST API calls (GET, POST, etc.) after these actions.

`ConnectyCube.chat.disconnect()` will close WebSocket and you won't be able to use chat for WebRTC (video/audio calls).
You should close only the WebRTC session after a call ends.

The error in the screenshot above means that you isn't able to use chat connection (the `ConnectyCube.chat.disconnect()` was called), but you are trying to send some messages via chat.

I am trying to advise you not to use the method `finishSession()`  after the end of each call

**Comment by alxx28** [comment]
Hi, @ccvlad
I already undestood, I think now is working well and the problem with local stream is null, is not present anymore, I can use mute and unmute several times without refreshing the page, but now I have other problem with the video call when is realized between web apps but I have to rewrite several things, I wish you could help me with that when I have ready project.

Thanks

**Comment by ccvlad** [comment]
Great! Just create a new issue when needed
