### ISSUE TITLE
Display message with html format

### ISSUE THREAD

**Issue by ciamalaeaskan** [ConnectyCube/connectycube-web-samples#76]
Hi,
 I'm using our connectycube-web-samples on that we want  to use chat messages as html formatingt (like spacing, hyperlink, etc). Can you please help how to achieve that.

Thanks.

**Comment by ccvlad** [comment]
@ciamalaeaskan 
Any description ?

**Comment by ciamalaeaskan** [comment]
@ccvlad added

**Comment by ccvlad** [comment]
You are able to make html as string and insert to the DOM via the [innerHTML](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) method:

```javascript
document.getElementById('#messagesList')
  .innerHTML(`<div class="message "id="${message.id}">${message.body}</div>`)
```

Or use some template builder such as [handlebars](https://handlebarsjs.com/guide/#what-is-handlebars)
