### ISSUE TITLE
Bad Authentication data - 200 - POST /session

### ISSUE THREAD

**Issue by dozsolti** [ConnectyCube/connectycube-web-samples#77]
Hello,

I've made a POST to https://api.connectycube.com/session
```
{
 "application_id": my application id from dashboard,
 "auth_key": my auth key from dashboard,
 "nonce": generated with Math.floor(Math.random() * 10000),
 "timestamp": generated with Math.floor(Date.now() / 1000),
 "user":{
    "login": here some email,
    "password": here some password
 },
 "signature": generated by concating all the properties above and then HmacSha1 with my auth secret
}
```

But I've got status `200 OK` with this message:
```json
{
    "errors": [
        "Bad Authentication data. Unauthorized on remote side. Status: 401.Response \"{\\n  \\\"name\\\": \\\"UnauthorizedError\\\",\\n  \\\"message\\\": \\\"No authorization token was found\\\",\\n  \\\"stack\\\": \\\"UnauthorizedError: No authorization token was found\\\\n    at middleware (/usr/src/app/node_modules/express-jwt/lib/index.js:76:21)\\\\n    at module.exports (/usr/src/app/api/policies/isAuthenticated.js:38:4)\\\\n \""
    ]
}
```

**Comment by DaveLomber** [comment]
@dozsolti please share what you set in Admin panel for Custom Identity Provider

**Comment by dozsolti** [comment]
I've set the API URL to my endpoint which if correctly called returns a  { user: { id: here some uuid, name: "John doe" ... }}
the request headers to { "Authorization" : "Bearer #{token}"}
and response params to  {"uid": "#{user.id}"}

**Comment by DaveLomber** [comment]
So, you have the following settings set in admin panel:

- request params: no
- request headers: { "Authorization" : "Bearer #{token}"}
- response params: {"uid": "#{user.id}"}

correct? 

If yes, what is supposed to be in 'token' param? 
You pass 'login' and 'password' - so you can use these fields only there

**Comment by dozsolti** [comment]
yes, partly, I was mean login instead of token, so it will be:
- request headers: { "Authorization" : "Bearer #{login}"}
- request params: empty
- response params: {"uid": "#{user.id}"}
- allow reuse ConnectyCube user: false

Why should I pass the login **and password**? The [documentation](https://developers.connectycube.com/guides/custom-identity-provider?id=login-flow-diagram) talks only about a login which is my IP_user_token(it will be a jwt)

**Comment by DaveLomber** [comment]
@dozsolti we will update the doc, or even better - make a password field as non mandatory if CIdP is enabled.
As for now - just pass any random value in a password field

**Comment by dozsolti** [comment]
Alright, I will try it later this week and come back with the results

**Comment by dozsolti** [comment]
Still not working... Do I missed something?

**First** I make `POST` to `https://api.connectycube.com/session` like this
![image](https://user-images.githubusercontent.com/17215747/107741554-155c2300-6d16-11eb-9c5a-8aa0c23110de.png)


**Second** I make a `POST` to `https://api.connectycube.com/login`
![image](https://user-images.githubusercontent.com/17215747/107741394-c0201180-6d15-11eb-8b95-a8969cb7e0c7.png)

![image](https://user-images.githubusercontent.com/17215747/107741450-dcbc4980-6d15-11eb-872f-dc6e55dc9fc6.png)

**And** for the Settings I have:

![image](https://user-images.githubusercontent.com/17215747/107741675-4fc5c000-6d16-11eb-9506-e2aff01ed035.png)

This is what I get from that endpoint from settings
![image](https://user-images.githubusercontent.com/17215747/107742169-32ddbc80-6d17-11eb-86d3-a41d6741205e.png)

Note: I try to login with a user which exist only in our server not on Connecty Cube, but this shouldn't be a problem

**Comment by dozsolti** [comment]
It worked, thank you!

**Comment by dozsolti** [comment]
Also how can I set the other details on user?
I've tried with in Response params:
```json
{
   "uid": "#{user.id}",
   "full_name": "#{user.firstName} #{user.lastName}",
   "avatar": "#{user.avatar}"
}
```

Looks like the full_name ***doesnt' support 2 variables*** because I'm getting ***status 500***.
Also it will be an issues if my avatar will be `null`?

**Comment by DaveLomber** [comment]
No issue if avatar is null 

As for now, you can map only
- full_name(optional)
- email(optional)
- login(optional)
- external_user_id(optional)

an only simple mapping like `"full_name": "#{user. full_name}"`

do you have any issues with it?

**Comment by dozsolti** [comment]
yes, I have the name of the user separated (first and last name) and I want to combine them
