### ISSUE TITLE
Video Call suddenly stopped working in chrome

### ISSUE THREAD

**Issue by alxx28** [ConnectyCube/connectycube-web-samples#83]
@ccvlad
Hello, I have my web app and mobile app almost ready, but I am testing in chrome and the video call is not working anymore, the strange thing is that in mozilla is working normally, in the console I don't see errors, the only thing that I see is that is not executed the source code fragment where the remote stream is assigned, only the localStream is being assigned.

```
function setStream(session, userID, remoteStream) {
            console.log('Remote Stream Assigned');
            session.attachMediaStream('vd_video2', remoteStream);
            $('#btn_mutesound').off('click').on('click', {x: session, y: 'unmute'}, setSound);
            $('#btn_unmutesound').off('click').on('click', {x: session, y: 'mute'}, setSound);
            $('#btn_mutevideo').off('click').on('click', {x: session, y: 'unmute'}, setVideo);
            $('#btn_unmutevideo').off('click').on('click', {x: session, y: 'mute'}, setVideo);
        }

ConnectyCube.videochat.onRemoteStreamListener = setStream;
```
[Web App](https://cronhis.xyz/)
user: admin
password: 12345

[Mobile App](https://cronhis.xyz/files/apk(24-feb-21)-4.apk)

[Videos showing the problem](https://cronhis.xyz/files/)

Users for the mobile app:
11000000
78000000
4000000

[Source Code Web App at the end of this:](https://cronhis.xyz/js/historia/consultaexterna/consultaexterna.js)

**Comment by DaveLomber** [comment]
@alxx28 is this still actual? 

You mean `onRemoteStreamListener ` is not called at Chrome side?

**Comment by alxx28** [comment]
Yes, I think that is the problem. I also tested in Opera and is workink normally, the prolem is in browsers based on chrome.
ConnectyCube Used Version is 3.7.1

**Comment by DaveLomber** [comment]
@alxx28 I tried to access calling in your Demo app, but seems no one is answering when I'm calling. 
Is there any other steps we need to follow to setup a working call?

**Comment by DaveLomber** [comment]
Also please confirm whether the standard p2p calling code sample working well at your side in Chrome https://github.com/ConnectyCube/connectycube-web-samples/tree/master/videochat

**Comment by alxx28** [comment]
The video calling between web apps is working well, the problem is between my web app and my android mobil app, you have to use the main web app and the mobile app.
Web app: [https://cronhis.xyz/index.php](url)
user: admin
password: 12345
After Login: https://cronhis.xyz/php/historia/consultaexterna/index.php
Then select then record with number 11000000

![image](https://user-images.githubusercontent.com/3847133/116907350-1317af80-ac07-11eb-8735-723d12989423.png)


Mobile app: [https://cronhis.xyz/files/apk(24-feb-21)-4.apk](url)

User for the mobile app:
11000000

In the mobile app: 
![web](https://user-images.githubusercontent.com/3847133/116907690-87525300-ac07-11eb-8fac-4430729dd4c4.jpeg)
