### ISSUE TITLE
Listen to Other Party Mute/Unmute Events

### ISSUE THREAD

**Issue by Abdulrahmanh995** [ConnectyCube/connectycube-web-samples#84]
Hi

How can video call other party listen to my mute/unmute events?

So when I mute the video, the other party can shows that I've disabled the video or the audio for example.

**Comment by Abdulrahmanh95** [comment]
@ccvlad 
`ConnectyCube.chat.onSystemMessageListener` is never being invoked.

I'm registering this callback after initializing the chat
`await ConnectyCube.chat.connect({
            userId: this.userId,
            password: this.currentSessionToken,
        });`

`ConnectyCube.chat.onSystemMessageListener = (msg) => {
            console.log('ConnectyCube.chat.onSystemMessageListener msg', msg);
            debugger;
        };`

Is there any working example for system messages?

**Comment by DaveLomber** [comment]
System messages reference:
- documentation https://developers.connectycube.com/js/messaging?id=system-messages#system-messages
- React conference chat code sample https://github.com/ConnectyCube/connectycube-web-samples/blob/master/videochat-conf-react/src/services/call-service.js#L167
