### ISSUE TITLE
Issue latest connectycube version with create-react-app

### ISSUE THREAD

**Issue by davidkhanpk** [ConnectyCube/connectycube-web-samples#89]
I am integrating connectycube web samples with my create-react-app.
But my app is crashing with this error: 

./node_modules/connectycube/lib/cubeMeeting.js
Support for the experimental syntax 'classProperties' isn't currently enabled (11:7):

react version: 16.31.1
connectycube version : 3.8.0 (latest)
OS: Windows 10
NodeJS Version: 12.15.0

**Comment by davidkhanpk** [comment]
I installed @babel/plugin-proposal-class-properties and added a .babelrc config file with this settings 
`{
    "plugins": [
      ["@babel/plugin-proposal-class-properties", { "loose": true }]
    ]
  }`
  But this issue is still not resolving.

**Comment by augustomatosdev** [comment]
Same for me, @davidkhanpk  have you found a solution already?

**Comment by davidkhanpk** [comment]
@augustomatosdev This issue occurs in later versions of 1.8.1.

**Comment by DaveLomber** [comment]
The new SDK 4.0 has been released https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/4.0.0 with full TypeScript support, please give it a try and let us know if the issue is still occures
