### ISSUE TITLE
Issue creating a session with user authorization

### ISSUE THREAD

**Issue by jesse45** [ConnectyCube/connectycube-web-samples#90]
I am trying to create a session with user authorization using the server api but it keeps giving me an error of 
422 'Unprocessable Entity' 
{"errors":["Unexpected signature"]}

Here is the code. I am using 
nodejs 15.14.0
expressjs 4.17.1

`const hash1 = require("crypto-js");
const fetch = require('node-fetch');

module.exports = async function (req, res, next) {

    //create json body
    let max = 9999999999;
    let min = 1000000000;
    let randomNonce = Math.floor(Math.random() * (max - min) + min);
    let timestamp = Date.now() / 1000;
    let authKey = "aDRceQyTXSYEdJU";
    let appId = 3610;

    let sign = hash1.HmacSHA1(`application_id=3610&auth_key=aDRceQyTXSYEdJU&nonce=${randomNonce}&timestamp=${timestamp}`, "dBV2PdhYMnruSMb")
    let base64 = sign.toString()

    const session = {
        application_id: appId,
        auth_key: authKey,
        nonce: randomNonce,
        timestamp: timestamp,
        signature: base64,
        user: {
            login: 'john_wick',
            password: 123456789
        }
    }

    fetch("https://api.connectycube.com/session", {
        method: 'POST',
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(session )

    })
        .then(response => {
            if (!response.ok) {
                throw Error(`Error message: ${response.statusText}`)
            }
            return response.json()
        })
        .then(data => {
            console.log(data)
            res.locals.session_token = data.session.token;
            console.log(`req.token: ${res.locals.session_token}`);
            if (req.originalUrl == "/auth/login") {
                res.locals.session = data.session;
            }
            next();

        })
        .catch(error => {
            console.log(error)
            next();
        })

}`
![image_2021-04-17_025010](https://user-images.githubusercontent.com/20870852/115105972-9fe41d00-9f27-11eb-917f-14c5eb29bac1.png)

the user is already in my users list
![image_2021-04-17_034229](https://user-images.githubusercontent.com/20870852/115107188-eee18080-9f2e-11eb-85e7-0c927ad66fe4.png)

**Comment by banshiAnton** [comment]
Hi @jesse45 you first SHA1 argument should look like
```javascript
`application_id=${app_id}&auth_key=${auth_key}&nonce=${nonce}&timestamp=${timestamp}&user[login]=${user_login}&user[password]=${user_password}`
```

**Comment by jesse45** [comment]
@banshiAnton thanks. Your solution worked.
