### ISSUE TITLE
Problem when send messages between Vuejs Project (JS) and Flutter APP

### ISSUE THREAD

**Issue by henriquetroiano** [ConnectyCube/connectycube-web-samples#93]
My email that i used to buy the service: rrnpbusiness@gmail.com

I got one problem:
When i send a message to mobile app in Flutter (or from Flutter to Web Version) i give a undefined error on console and the Connectycube Javascript bricks, so I need to reload the page to everthing goes back to normal.

Like the image following:
![err](https://user-images.githubusercontent.com/63327237/116753565-a66d9c80-a9dd-11eb-88e1-fb72c61b69c8.PNG)

When I use the chat on desktop version, in VueJs, to talk with other person or group in the Web version, nothing wrong happens.

Any idea of what's wrong?

**Comment by henriquetroiano** [comment]
![2](https://user-images.githubusercontent.com/63327237/116753782-049a7f80-a9de-11eb-9d66-9763f33acb21.PNG)

**Comment by henriquetroiano** [comment]
An on mobile APP i got a "EMPTY" message, like following:

![WhatsApp Image 2021-04-30 at 6 02 21 PM](https://user-images.githubusercontent.com/63327237/116753908-41667680-a9de-11eb-87e6-1e33354e296f.jpeg)

**Comment by henriquetroiano** [comment]
![image](https://user-images.githubusercontent.com/63327237/117151321-5735bc00-ad8f-11eb-9262-28552f8d3ea8.png)
this is the callback typing listener

![image](https://user-images.githubusercontent.com/63327237/117151398-6ae12280-ad8f-11eb-8873-a3e192fe959f.png)
and this is the problem when i press "send" on flutter

**Comment by henriquetroiano** [comment]
the problem occours with the default flutter example  too

**Comment by henriquetroiano** [comment]
I havo no time to wait...

**Comment by henriquetroiano** [comment]
Hi there! any updates?

**Comment by DaveLomber** [comment]
@henriquetroiano the log does look well, 
we are checking for more

what version of JS SDK you use?

**Comment by DaveLomber** [comment]
Also, can you click on the 1st stack trace line and see what will it display.
Then please share this peace of code. Cause It's nor clear where it found 'length' operator, as we do not see any of it inside SDK

**Comment by henriquetroiano** [comment]
![image](https://user-images.githubusercontent.com/63327237/117308025-7ef05700-ae57-11eb-9caf-daa2084ea604.png)

the sdk version is 3.9.0 i think, i'd installed by npm install

**Comment by henriquetroiano** [comment]
I think its something wrong with the callback from flutter to web (I THINK).
the only callback from flutter to web that its working is the Typing callback. 
To see it working, i need to let the chat opened on flutter before open the web chat.
Because if I open the chat with the web version already running, i got some "length" errors.
So, this is the callback:
![image](https://user-images.githubusercontent.com/63327237/117309937-4782aa00-ae59-11eb-8160-78d0dba8cb70.png)

Do you see? i Dont receive the Dialog_id on callback.

**Comment by henriquetroiano** [comment]
![image](https://user-images.githubusercontent.com/63327237/117310799-00e17f80-ae5a-11eb-9405-705566e5690d.png)

Dependencies, Vue Version, etc

**Comment by DaveLomber** [comment]
@henriquetroiano can you please do this 

https://github.com/ConnectyCube/connectycube-web-samples/issues/93#issuecomment-833526073

**Comment by henriquetroiano** [comment]
Sorry

![image](https://user-images.githubusercontent.com/63327237/117321121-3dfe3f80-ae63-11eb-896f-8fab130eefe1.png)

the full trace here

**Comment by DaveLomber** [comment]
no, I mean something diff 

<img width="1063" alt="Screenshot 2021-05-06 at 18 11 11" src="https://user-images.githubusercontent.com/39332586/117322297-8d119800-ae96-11eb-9ca5-2582827be2c1.png">

Click on it

and then share what you see

**Comment by henriquetroiano** [comment]
here is the error and the trace:
![image](https://user-images.githubusercontent.com/63327237/117332788-a0a90880-ae6e-11eb-9968-936ad9278b16.png)

trace:
![image](https://user-images.githubusercontent.com/63327237/117332820-aa327080-ae6e-11eb-94e2-49b182f0e7da.png)

**Comment by DaveLomber** [comment]
@henriquetroiano could you please also scroll to the right to see the exact place it fails  - lime 692

**Comment by henriquetroiano** [comment]
![image](https://user-images.githubusercontent.com/63327237/117370717-33609c00-ae9d-11eb-9992-e895b6e77788.png)

there is no other relevant information at the right side, i think

**Comment by henriquetroiano** [comment]
Do you have good news?

**Comment by DaveLomber** [comment]
@henriquetroiano I brought Flutter dev to check the issue, 
we are working together towards the resolution
Will update you around tomorrow

**Comment by DaveLomber** [comment]
So the root cause is

```
/node_modules/connectycube/lib/messaging/cubeChatInternalUtils.js:195
      if (extraParams.children[c].children.length === 1) {
      
      
TypeError: Cannot read property 'length' of undefined
```

**Comment by DaveLomber** [comment]
<img width="621" alt="Screenshot 2021-05-12 at 14 12 06" src="https://user-images.githubusercontent.com/39332586/117966061-296eeb00-b32c-11eb-91be-420e773d7bfd.png">

the root cause seems relates to an extra line break symbol which comes as a part of XML from Flutter side 

I will talk to Flutter dev to fix it at Flutter SDK side

**Comment by DaveLomber** [comment]
@TatankaConCube please adjust if possible at Flutter side

**Comment by henriquetroiano** [comment]
We had to stop the project because the is the main functionality of our app (chat and video). Can you please update as soon as possible?
What i need to do here? just update the flutter packages?
Thanks in advance

**Comment by TatankaConCube** [comment]
We will do it at tomorrow morning. I made fixes today, tomorrow we will check them together with JS team one more time and if all ok I publish new version of Flutter SDK.

**Comment by DaveLomber** [comment]
@henriquetroiano 

- new JS SDK with Flutter SDK interop support is released https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/3.9.2
- new Flutter SDK to be release in 1-2h

**Comment by TatankaConCube** [comment]
@henriquetroiano we released version [2.0.0-nullsafety.4](https://pub.dev/packages/connectycube_sdk/versions/2.0.0-nullsafety.4) with required fixes. Please use it with updated JS SDK.

**Comment by henriquetroiano** [comment]
@DaveLomber @TatankaConCube thank you both. I'll update the SDK js and flutter.

**Comment by henriquetroiano** [comment]
I'm facing a lot of problems by updating the flutter from 1.22 to 2.0.6, because you made the update requires Dart 2.12! did you have a updated Code example of chat in flutter?

**Comment by henriquetroiano** [comment]
My entire project was developed thinking to use the flutter 1.22, i don't have time to update all

**Comment by henriquetroiano** [comment]
I need to apply this fix on connectycube_sdk: ^1.1.2, if its only a extra breakline on xml, am i able to fix by myself?

**Comment by henriquetroiano** [comment]
Everybody whose used the example app based on dart 2.10 needs to update to flutter 2? i dont have time to do it, seriously.

**Comment by TatankaConCube** [comment]
@henriquetroiano unfortunately, you can't fix it by yourself. But we updated our Chat sample for the nullsafety feature support in branch [null_safety](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/feature/null_safety) and you can use it for your tests (don't forget to update the connectycube_sdk there to the latest version).

**Comment by henriquetroiano** [comment]
But our app is all based on Dart 2.10, we cant update to dart 2.12 and flutter too. can you please make the changes for the dart 2.10?

**Comment by henriquetroiano** [comment]
We were not advised that this update would depend of dart 2.12. We were not waiting for it.

**Comment by TatankaConCube** [comment]
it doesn't make sense, all apps in near future will be updated to dart 2.12

**Comment by henriquetroiano** [comment]
The bug was on flutter 1 and you made a fix for flutter 2. After 1 year, I'm sure Twilio is too much better than Connectycube.

**Comment by TatankaConCube** [comment]
To be honest, We do not compete with Twilio, since we are on diff weight classes.
Let us know if there is anything we can help you with
