### ISSUE TITLE
Problem when try to connect to chat with token

### ISSUE THREAD

**Issue by henriquetroiano** [ConnectyCube/connectycube-web-samples#94]
![image](https://user-images.githubusercontent.com/63327237/117175658-763f4880-ada5-11eb-8fc2-78328cf9d484.png)

I'm facing this problem when i try to login using a backend-generated token. It was working until yesterday.

**Comment by DaveLomber** [comment]
We are investigation re root cause

Will update shortly with more info

Thank you for raising the issue

**Comment by DaveLomber** [comment]
@henriquetroiano the root cause is identified, 
the fix is on the waY

**Comment by DaveLomber** [comment]
@henriquetroiano the patch is applied on server 

Please let us know  whether the issue is resolved

**Comment by henriquetroiano** [comment]
Thank you for the support. It working now. I'll close this issue. Any update for the issue number 93?

**Comment by henriquetroiano** [comment]
![image](https://user-images.githubusercontent.com/63327237/117665075-d99bf280-b178-11eb-939c-c9a2b3606e91.png)

Im opening again, because i'm facing again the same issue.

**Comment by DaveLomber** [comment]
@henriquetroiano it seems you are trying to connect to chat with empty user id and empty password

Just make sure it's all provided before connecting to chat

**Comment by henriquetroiano** [comment]
Sorry, my mistake.
