### ISSUE TITLE
No dialogID on onMessageTypingListener

### ISSUE THREAD

**Issue by curtu** [ConnectyCube/connectycube-web-samples#95]
in your [documentation ](https://developers.connectycube.com/js/messaging?id=_39is-typing39-status) you say that on the **onMessageTypingListener** i should receive the dialogId. But it is always null

The problem is when i have multiple dialogs(1:1, and group) with the same user and i don't know where he is typing.

**Comment by DaveLomber** [comment]
Do you pass a dialog id when you start typing?

Means here https://developers.connectycube.com/js/messaging?id=_39is-typing39-status

// const dialogJid = ..; // for group chat

**Comment by curtu** [comment]
but how can i get the dialogID for chat 1:1?

**Comment by curtu** [comment]
> Do you pass a dialog id when you start typing?
> 
> Means here https://developers.connectycube.com/js/messaging?id=_39is-typing39-status
> 
> // const dialogJid = ..; // for group chat

for 1:1 chat in the documentation there is no passing the dialogID, only the opponentID.
i passed the dialog.id too but nothingh changes. On onMessageTypingListener i don't receive the dialogID

**Comment by DaveLomber** [comment]
for 1-1 chat please pass a user id
for group chat please pass dialog id or dialog jid

**Comment by curtu** [comment]
okey. thank you
